// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.33.5
// source: combos.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";

export const protobufPackage = "zmk.combos";

export enum SetComboErrorCode {
  SET_COMBO_ERR_OK = 0,
  SET_COMBO_ERR_GENERIC = 1,
  SET_COMBO_ERR_INVALID_INDEX = 2,
  SET_COMBO_ERR_INVALID_BINDING = 3,
  SET_COMBO_ERR_UNSUPPORTED_FIELD = 4,
  UNRECOGNIZED = -1,
}

export function setComboErrorCodeFromJSON(object: any): SetComboErrorCode {
  switch (object) {
    case 0:
    case "SET_COMBO_ERR_OK":
      return SetComboErrorCode.SET_COMBO_ERR_OK;
    case 1:
    case "SET_COMBO_ERR_GENERIC":
      return SetComboErrorCode.SET_COMBO_ERR_GENERIC;
    case 2:
    case "SET_COMBO_ERR_INVALID_INDEX":
      return SetComboErrorCode.SET_COMBO_ERR_INVALID_INDEX;
    case 3:
    case "SET_COMBO_ERR_INVALID_BINDING":
      return SetComboErrorCode.SET_COMBO_ERR_INVALID_BINDING;
    case 4:
    case "SET_COMBO_ERR_UNSUPPORTED_FIELD":
      return SetComboErrorCode.SET_COMBO_ERR_UNSUPPORTED_FIELD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SetComboErrorCode.UNRECOGNIZED;
  }
}

export function setComboErrorCodeToJSON(object: SetComboErrorCode): string {
  switch (object) {
    case SetComboErrorCode.SET_COMBO_ERR_OK:
      return "SET_COMBO_ERR_OK";
    case SetComboErrorCode.SET_COMBO_ERR_GENERIC:
      return "SET_COMBO_ERR_GENERIC";
    case SetComboErrorCode.SET_COMBO_ERR_INVALID_INDEX:
      return "SET_COMBO_ERR_INVALID_INDEX";
    case SetComboErrorCode.SET_COMBO_ERR_INVALID_BINDING:
      return "SET_COMBO_ERR_INVALID_BINDING";
    case SetComboErrorCode.SET_COMBO_ERR_UNSUPPORTED_FIELD:
      return "SET_COMBO_ERR_UNSUPPORTED_FIELD";
    case SetComboErrorCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Request {
  listAllCombos?: boolean | undefined;
  getCombo?: GetComboRequest | undefined;
  setCombo?: SetComboRequest | undefined;
}

export interface Response {
  listAllCombos?: ListAllCombosResponse | undefined;
  getCombo?: ComboConfig | undefined;
  setCombo?: SetComboResponse | undefined;
}

export interface Notification {
  combosChanged?: boolean | undefined;
}

export interface ComboConfig {
  index: number;
  timeoutMs: number;
  requirePriorIdleMs: number;
  slowRelease: boolean;
  layerMask: number;
  behavior: BehaviorBinding | undefined;
  keyPositions: number[];
  editableBehavior: boolean;
  editableKeyPositions: boolean;
}

export interface ListAllCombosResponse {
  combos: ComboConfig[];
}

export interface GetComboRequest {
  index: number;
}

export interface SetComboRequest {
  index: number;
  combo: ComboConfig | undefined;
}

export interface SetComboResponse {
  ok?: boolean | undefined;
  err?: SetComboErrorCode | undefined;
}

function createBaseRequest(): Request {
  return { listAllCombos: undefined, getCombo: undefined, setCombo: undefined };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.listAllCombos !== undefined) {
      writer.uint32(8).bool(message.listAllCombos);
    }
    if (message.getCombo !== undefined) {
      GetComboRequest.encode(message.getCombo, writer.uint32(18).fork()).ldelim();
    }
    if (message.setCombo !== undefined) {
      SetComboRequest.encode(message.setCombo, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.listAllCombos = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getCombo = GetComboRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setCombo = SetComboRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      listAllCombos: isSet(object.listAllCombos) ? globalThis.Boolean(object.listAllCombos) : undefined,
      getCombo: isSet(object.getCombo) ? GetComboRequest.fromJSON(object.getCombo) : undefined,
      setCombo: isSet(object.setCombo) ? SetComboRequest.fromJSON(object.setCombo) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.listAllCombos !== undefined) {
      obj.listAllCombos = message.listAllCombos;
    }
    if (message.getCombo !== undefined) {
      obj.getCombo = GetComboRequest.toJSON(message.getCombo);
    }
    if (message.setCombo !== undefined) {
      obj.setCombo = SetComboRequest.toJSON(message.setCombo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.listAllCombos = object.listAllCombos ?? undefined;
    message.getCombo = (object.getCombo !== undefined && object.getCombo !== null)
      ? GetComboRequest.fromPartial(object.getCombo)
      : undefined;
    message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
      ? SetComboRequest.fromPartial(object.setCombo)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { listAllCombos: undefined, getCombo: undefined, setCombo: undefined };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.listAllCombos !== undefined) {
      ListAllCombosResponse.encode(message.listAllCombos, writer.uint32(10).fork()).ldelim();
    }
    if (message.getCombo !== undefined) {
      ComboConfig.encode(message.getCombo, writer.uint32(18).fork()).ldelim();
    }
    if (message.setCombo !== undefined) {
      SetComboResponse.encode(message.setCombo, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.listAllCombos = ListAllCombosResponse.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.getCombo = ComboConfig.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setCombo = SetComboResponse.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      listAllCombos: isSet(object.listAllCombos) ? ListAllCombosResponse.fromJSON(object.listAllCombos) : undefined,
      getCombo: isSet(object.getCombo) ? ComboConfig.fromJSON(object.getCombo) : undefined,
      setCombo: isSet(object.setCombo) ? SetComboResponse.fromJSON(object.setCombo) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.listAllCombos !== undefined) {
      obj.listAllCombos = ListAllCombosResponse.toJSON(message.listAllCombos);
    }
    if (message.getCombo !== undefined) {
      obj.getCombo = ComboConfig.toJSON(message.getCombo);
    }
    if (message.setCombo !== undefined) {
      obj.setCombo = SetComboResponse.toJSON(message.setCombo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.listAllCombos = (object.listAllCombos !== undefined && object.listAllCombos !== null)
      ? ListAllCombosResponse.fromPartial(object.listAllCombos)
      : undefined;
    message.getCombo = (object.getCombo !== undefined && object.getCombo !== null)
      ? ComboConfig.fromPartial(object.getCombo)
      : undefined;
    message.setCombo = (object.setCombo !== undefined && object.setCombo !== null)
      ? SetComboResponse.fromPartial(object.setCombo)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { combosChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.combosChanged !== undefined) {
      writer.uint32(8).bool(message.combosChanged);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.combosChanged = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return { combosChanged: isSet(object.combosChanged) ? globalThis.Boolean(object.combosChanged) : undefined };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.combosChanged !== undefined) {
      obj.combosChanged = message.combosChanged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.combosChanged = object.combosChanged ?? undefined;
    return message;
  },
};

function createBaseComboConfig(): ComboConfig {
  return {
    index: 0,
    timeoutMs: 0,
    requirePriorIdleMs: 0,
    slowRelease: false,
    layerMask: 0,
    behavior: undefined,
    keyPositions: [],
    editableBehavior: false,
    editableKeyPositions: false,
  };
}

export const ComboConfig = {
  encode(message: ComboConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(16).int32(message.timeoutMs);
    }
    if (message.requirePriorIdleMs !== 0) {
      writer.uint32(24).int32(message.requirePriorIdleMs);
    }
    if (message.slowRelease !== false) {
      writer.uint32(32).bool(message.slowRelease);
    }
    if (message.layerMask !== 0) {
      writer.uint32(40).uint32(message.layerMask);
    }
    if (message.behavior !== undefined) {
      BehaviorBinding.encode(message.behavior, writer.uint32(50).fork()).ldelim();
    }
    writer.uint32(58).fork();
    for (const v of message.keyPositions) {
      writer.uint32(v);
    }
    writer.ldelim();
    if (message.editableBehavior !== false) {
      writer.uint32(64).bool(message.editableBehavior);
    }
    if (message.editableKeyPositions !== false) {
      writer.uint32(72).bool(message.editableKeyPositions);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ComboConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComboConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.timeoutMs = reader.int32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.requirePriorIdleMs = reader.int32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.slowRelease = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.layerMask = reader.uint32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.behavior = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag === 56) {
            message.keyPositions.push(reader.uint32());

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.keyPositions.push(reader.uint32());
            }

            continue;
          }

          break;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.editableBehavior = reader.bool();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.editableKeyPositions = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComboConfig {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      timeoutMs: isSet(object.timeoutMs) ? globalThis.Number(object.timeoutMs) : 0,
      requirePriorIdleMs: isSet(object.requirePriorIdleMs) ? globalThis.Number(object.requirePriorIdleMs) : 0,
      slowRelease: isSet(object.slowRelease) ? globalThis.Boolean(object.slowRelease) : false,
      layerMask: isSet(object.layerMask) ? globalThis.Number(object.layerMask) : 0,
      behavior: isSet(object.behavior) ? BehaviorBinding.fromJSON(object.behavior) : undefined,
      keyPositions: globalThis.Array.isArray(object?.keyPositions)
        ? object.keyPositions.map((e: any) => globalThis.Number(e))
        : [],
      editableBehavior: isSet(object.editableBehavior) ? globalThis.Boolean(object.editableBehavior) : false,
      editableKeyPositions: isSet(object.editableKeyPositions)
        ? globalThis.Boolean(object.editableKeyPositions)
        : false,
    };
  },

  toJSON(message: ComboConfig): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    if (message.requirePriorIdleMs !== 0) {
      obj.requirePriorIdleMs = Math.round(message.requirePriorIdleMs);
    }
    if (message.slowRelease !== false) {
      obj.slowRelease = message.slowRelease;
    }
    if (message.layerMask !== 0) {
      obj.layerMask = Math.round(message.layerMask);
    }
    if (message.behavior !== undefined) {
      obj.behavior = BehaviorBinding.toJSON(message.behavior);
    }
    if (message.keyPositions?.length) {
      obj.keyPositions = message.keyPositions.map((e) => Math.round(e));
    }
    if (message.editableBehavior !== false) {
      obj.editableBehavior = message.editableBehavior;
    }
    if (message.editableKeyPositions !== false) {
      obj.editableKeyPositions = message.editableKeyPositions;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComboConfig>, I>>(base?: I): ComboConfig {
    return ComboConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComboConfig>, I>>(object: I): ComboConfig {
    const message = createBaseComboConfig();
    message.index = object.index ?? 0;
    message.timeoutMs = object.timeoutMs ?? 0;
    message.requirePriorIdleMs = object.requirePriorIdleMs ?? 0;
    message.slowRelease = object.slowRelease ?? false;
    message.layerMask = object.layerMask ?? 0;
    message.behavior = (object.behavior !== undefined && object.behavior !== null)
      ? BehaviorBinding.fromPartial(object.behavior)
      : undefined;
    message.keyPositions = object.keyPositions?.map((e) => e) || [];
    message.editableBehavior = object.editableBehavior ?? false;
    message.editableKeyPositions = object.editableKeyPositions ?? false;
    return message;
  },
};

function createBaseListAllCombosResponse(): ListAllCombosResponse {
  return { combos: [] };
}

export const ListAllCombosResponse = {
  encode(message: ListAllCombosResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.combos) {
      ComboConfig.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListAllCombosResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAllCombosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.combos.push(ComboConfig.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListAllCombosResponse {
    return {
      combos: globalThis.Array.isArray(object?.combos) ? object.combos.map((e: any) => ComboConfig.fromJSON(e)) : [],
    };
  },

  toJSON(message: ListAllCombosResponse): unknown {
    const obj: any = {};
    if (message.combos?.length) {
      obj.combos = message.combos.map((e) => ComboConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAllCombosResponse>, I>>(base?: I): ListAllCombosResponse {
    return ListAllCombosResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAllCombosResponse>, I>>(object: I): ListAllCombosResponse {
    const message = createBaseListAllCombosResponse();
    message.combos = object.combos?.map((e) => ComboConfig.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetComboRequest(): GetComboRequest {
  return { index: 0 };
}

export const GetComboRequest = {
  encode(message: GetComboRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetComboRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetComboRequest {
    return { index: isSet(object.index) ? globalThis.Number(object.index) : 0 };
  },

  toJSON(message: GetComboRequest): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetComboRequest>, I>>(base?: I): GetComboRequest {
    return GetComboRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetComboRequest>, I>>(object: I): GetComboRequest {
    const message = createBaseGetComboRequest();
    message.index = object.index ?? 0;
    return message;
  },
};

function createBaseSetComboRequest(): SetComboRequest {
  return { index: 0, combo: undefined };
}

export const SetComboRequest = {
  encode(message: SetComboRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.index !== 0) {
      writer.uint32(8).uint32(message.index);
    }
    if (message.combo !== undefined) {
      ComboConfig.encode(message.combo, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetComboRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetComboRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.index = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.combo = ComboConfig.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetComboRequest {
    return {
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      combo: isSet(object.combo) ? ComboConfig.fromJSON(object.combo) : undefined,
    };
  },

  toJSON(message: SetComboRequest): unknown {
    const obj: any = {};
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.combo !== undefined) {
      obj.combo = ComboConfig.toJSON(message.combo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetComboRequest>, I>>(base?: I): SetComboRequest {
    return SetComboRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetComboRequest>, I>>(object: I): SetComboRequest {
    const message = createBaseSetComboRequest();
    message.index = object.index ?? 0;
    message.combo = (object.combo !== undefined && object.combo !== null)
      ? ComboConfig.fromPartial(object.combo)
      : undefined;
    return message;
  },
};

function createBaseSetComboResponse(): SetComboResponse {
  return { ok: undefined, err: undefined };
}

export const SetComboResponse = {
  encode(message: SetComboResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ok !== undefined) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.err !== undefined) {
      writer.uint32(16).int32(message.err);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetComboResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetComboResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.err = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetComboResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : undefined,
      err: isSet(object.err) ? setComboErrorCodeFromJSON(object.err) : undefined,
    };
  },

  toJSON(message: SetComboResponse): unknown {
    const obj: any = {};
    if (message.ok !== undefined) {
      obj.ok = message.ok;
    }
    if (message.err !== undefined) {
      obj.err = setComboErrorCodeToJSON(message.err);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetComboResponse>, I>>(base?: I): SetComboResponse {
    return SetComboResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetComboResponse>, I>>(object: I): SetComboResponse {
    const message = createBaseSetComboResponse();
    message.ok = object.ok ?? undefined;
    message.err = object.err ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
