// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.33.5
// source: lighting.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "zmk.lighting";

export interface HsbColor {
  /** Hue: 0-359 */
  h: number;
  /** Saturation: 0-100 */
  s: number;
  /** Brightness: 0-100 */
  b: number;
}

export interface RgbUnderglowState {
  on: boolean;
  color: HsbColor | undefined;
  effect: number;
  speed: number;
  effectCount: number;
  effectNames: string[];
}

export interface SetRgbUnderglowStateRequest {
  on?: boolean | undefined;
  color?: HsbColor | undefined;
  effect?: number | undefined;
  speed?: number | undefined;
}

export interface BacklightState {
  on: boolean;
  brightness: number;
}

export interface SetBacklightStateRequest {
  on?: boolean | undefined;
  brightness?: number | undefined;
}

export interface Request {
  getRgbUnderglowState?: boolean | undefined;
  setRgbUnderglowState?: SetRgbUnderglowStateRequest | undefined;
  getBacklightState?: boolean | undefined;
  setBacklightState?: SetBacklightStateRequest | undefined;
  saveState?: boolean | undefined;
}

export interface Response {
  getRgbUnderglowState?: RgbUnderglowState | undefined;
  setRgbUnderglowState?: boolean | undefined;
  getBacklightState?: BacklightState | undefined;
  setBacklightState?: boolean | undefined;
  saveState?: boolean | undefined;
}

export interface Notification {
  rgbUnderglowStateChanged?: RgbUnderglowState | undefined;
  backlightStateChanged?: BacklightState | undefined;
}

function createBaseHsbColor(): HsbColor {
  return { h: 0, s: 0, b: 0 };
}

export const HsbColor = {
  encode(message: HsbColor, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.h !== 0) {
      writer.uint32(8).uint32(message.h);
    }
    if (message.s !== 0) {
      writer.uint32(16).uint32(message.s);
    }
    if (message.b !== 0) {
      writer.uint32(24).uint32(message.b);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HsbColor {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHsbColor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.h = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.s = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.b = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HsbColor {
    return {
      h: isSet(object.h) ? globalThis.Number(object.h) : 0,
      s: isSet(object.s) ? globalThis.Number(object.s) : 0,
      b: isSet(object.b) ? globalThis.Number(object.b) : 0,
    };
  },

  toJSON(message: HsbColor): unknown {
    const obj: any = {};
    if (message.h !== 0) {
      obj.h = Math.round(message.h);
    }
    if (message.s !== 0) {
      obj.s = Math.round(message.s);
    }
    if (message.b !== 0) {
      obj.b = Math.round(message.b);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HsbColor>, I>>(base?: I): HsbColor {
    return HsbColor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HsbColor>, I>>(object: I): HsbColor {
    const message = createBaseHsbColor();
    message.h = object.h ?? 0;
    message.s = object.s ?? 0;
    message.b = object.b ?? 0;
    return message;
  },
};

function createBaseRgbUnderglowState(): RgbUnderglowState {
  return { on: false, color: undefined, effect: 0, speed: 0, effectCount: 0, effectNames: [] };
}

export const RgbUnderglowState = {
  encode(message: RgbUnderglowState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== false) {
      writer.uint32(8).bool(message.on);
    }
    if (message.color !== undefined) {
      HsbColor.encode(message.color, writer.uint32(18).fork()).ldelim();
    }
    if (message.effect !== 0) {
      writer.uint32(24).uint32(message.effect);
    }
    if (message.speed !== 0) {
      writer.uint32(32).uint32(message.speed);
    }
    if (message.effectCount !== 0) {
      writer.uint32(40).uint32(message.effectCount);
    }
    for (const v of message.effectNames) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RgbUnderglowState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRgbUnderglowState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.color = HsbColor.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.effect = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.speed = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.effectCount = reader.uint32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.effectNames.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RgbUnderglowState {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : false,
      color: isSet(object.color) ? HsbColor.fromJSON(object.color) : undefined,
      effect: isSet(object.effect) ? globalThis.Number(object.effect) : 0,
      speed: isSet(object.speed) ? globalThis.Number(object.speed) : 0,
      effectCount: isSet(object.effectCount) ? globalThis.Number(object.effectCount) : 0,
      effectNames: globalThis.Array.isArray(object?.effectNames)
        ? object.effectNames.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: RgbUnderglowState): unknown {
    const obj: any = {};
    if (message.on !== false) {
      obj.on = message.on;
    }
    if (message.color !== undefined) {
      obj.color = HsbColor.toJSON(message.color);
    }
    if (message.effect !== 0) {
      obj.effect = Math.round(message.effect);
    }
    if (message.speed !== 0) {
      obj.speed = Math.round(message.speed);
    }
    if (message.effectCount !== 0) {
      obj.effectCount = Math.round(message.effectCount);
    }
    if (message.effectNames?.length) {
      obj.effectNames = message.effectNames;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RgbUnderglowState>, I>>(base?: I): RgbUnderglowState {
    return RgbUnderglowState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RgbUnderglowState>, I>>(object: I): RgbUnderglowState {
    const message = createBaseRgbUnderglowState();
    message.on = object.on ?? false;
    message.color = (object.color !== undefined && object.color !== null)
      ? HsbColor.fromPartial(object.color)
      : undefined;
    message.effect = object.effect ?? 0;
    message.speed = object.speed ?? 0;
    message.effectCount = object.effectCount ?? 0;
    message.effectNames = object.effectNames?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetRgbUnderglowStateRequest(): SetRgbUnderglowStateRequest {
  return { on: undefined, color: undefined, effect: undefined, speed: undefined };
}

export const SetRgbUnderglowStateRequest = {
  encode(message: SetRgbUnderglowStateRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== undefined) {
      writer.uint32(8).bool(message.on);
    }
    if (message.color !== undefined) {
      HsbColor.encode(message.color, writer.uint32(18).fork()).ldelim();
    }
    if (message.effect !== undefined) {
      writer.uint32(24).uint32(message.effect);
    }
    if (message.speed !== undefined) {
      writer.uint32(32).uint32(message.speed);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetRgbUnderglowStateRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetRgbUnderglowStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.color = HsbColor.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.effect = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.speed = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetRgbUnderglowStateRequest {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : undefined,
      color: isSet(object.color) ? HsbColor.fromJSON(object.color) : undefined,
      effect: isSet(object.effect) ? globalThis.Number(object.effect) : undefined,
      speed: isSet(object.speed) ? globalThis.Number(object.speed) : undefined,
    };
  },

  toJSON(message: SetRgbUnderglowStateRequest): unknown {
    const obj: any = {};
    if (message.on !== undefined) {
      obj.on = message.on;
    }
    if (message.color !== undefined) {
      obj.color = HsbColor.toJSON(message.color);
    }
    if (message.effect !== undefined) {
      obj.effect = Math.round(message.effect);
    }
    if (message.speed !== undefined) {
      obj.speed = Math.round(message.speed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetRgbUnderglowStateRequest>, I>>(base?: I): SetRgbUnderglowStateRequest {
    return SetRgbUnderglowStateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetRgbUnderglowStateRequest>, I>>(object: I): SetRgbUnderglowStateRequest {
    const message = createBaseSetRgbUnderglowStateRequest();
    message.on = object.on ?? undefined;
    message.color = (object.color !== undefined && object.color !== null)
      ? HsbColor.fromPartial(object.color)
      : undefined;
    message.effect = object.effect ?? undefined;
    message.speed = object.speed ?? undefined;
    return message;
  },
};

function createBaseBacklightState(): BacklightState {
  return { on: false, brightness: 0 };
}

export const BacklightState = {
  encode(message: BacklightState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== false) {
      writer.uint32(8).bool(message.on);
    }
    if (message.brightness !== 0) {
      writer.uint32(16).uint32(message.brightness);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BacklightState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBacklightState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.brightness = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BacklightState {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : false,
      brightness: isSet(object.brightness) ? globalThis.Number(object.brightness) : 0,
    };
  },

  toJSON(message: BacklightState): unknown {
    const obj: any = {};
    if (message.on !== false) {
      obj.on = message.on;
    }
    if (message.brightness !== 0) {
      obj.brightness = Math.round(message.brightness);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BacklightState>, I>>(base?: I): BacklightState {
    return BacklightState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BacklightState>, I>>(object: I): BacklightState {
    const message = createBaseBacklightState();
    message.on = object.on ?? false;
    message.brightness = object.brightness ?? 0;
    return message;
  },
};

function createBaseSetBacklightStateRequest(): SetBacklightStateRequest {
  return { on: undefined, brightness: undefined };
}

export const SetBacklightStateRequest = {
  encode(message: SetBacklightStateRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== undefined) {
      writer.uint32(8).bool(message.on);
    }
    if (message.brightness !== undefined) {
      writer.uint32(16).uint32(message.brightness);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBacklightStateRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBacklightStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.brightness = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBacklightStateRequest {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : undefined,
      brightness: isSet(object.brightness) ? globalThis.Number(object.brightness) : undefined,
    };
  },

  toJSON(message: SetBacklightStateRequest): unknown {
    const obj: any = {};
    if (message.on !== undefined) {
      obj.on = message.on;
    }
    if (message.brightness !== undefined) {
      obj.brightness = Math.round(message.brightness);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBacklightStateRequest>, I>>(base?: I): SetBacklightStateRequest {
    return SetBacklightStateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBacklightStateRequest>, I>>(object: I): SetBacklightStateRequest {
    const message = createBaseSetBacklightStateRequest();
    message.on = object.on ?? undefined;
    message.brightness = object.brightness ?? undefined;
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    getRgbUnderglowState: undefined,
    setRgbUnderglowState: undefined,
    getBacklightState: undefined,
    setBacklightState: undefined,
    saveState: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getRgbUnderglowState !== undefined) {
      writer.uint32(8).bool(message.getRgbUnderglowState);
    }
    if (message.setRgbUnderglowState !== undefined) {
      SetRgbUnderglowStateRequest.encode(message.setRgbUnderglowState, writer.uint32(18).fork()).ldelim();
    }
    if (message.getBacklightState !== undefined) {
      writer.uint32(24).bool(message.getBacklightState);
    }
    if (message.setBacklightState !== undefined) {
      SetBacklightStateRequest.encode(message.setBacklightState, writer.uint32(34).fork()).ldelim();
    }
    if (message.saveState !== undefined) {
      writer.uint32(40).bool(message.saveState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getRgbUnderglowState = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.setRgbUnderglowState = SetRgbUnderglowStateRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.getBacklightState = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.setBacklightState = SetBacklightStateRequest.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.saveState = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getRgbUnderglowState: isSet(object.getRgbUnderglowState)
        ? globalThis.Boolean(object.getRgbUnderglowState)
        : undefined,
      setRgbUnderglowState: isSet(object.setRgbUnderglowState)
        ? SetRgbUnderglowStateRequest.fromJSON(object.setRgbUnderglowState)
        : undefined,
      getBacklightState: isSet(object.getBacklightState) ? globalThis.Boolean(object.getBacklightState) : undefined,
      setBacklightState: isSet(object.setBacklightState)
        ? SetBacklightStateRequest.fromJSON(object.setBacklightState)
        : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getRgbUnderglowState !== undefined) {
      obj.getRgbUnderglowState = message.getRgbUnderglowState;
    }
    if (message.setRgbUnderglowState !== undefined) {
      obj.setRgbUnderglowState = SetRgbUnderglowStateRequest.toJSON(message.setRgbUnderglowState);
    }
    if (message.getBacklightState !== undefined) {
      obj.getBacklightState = message.getBacklightState;
    }
    if (message.setBacklightState !== undefined) {
      obj.setBacklightState = SetBacklightStateRequest.toJSON(message.setBacklightState);
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getRgbUnderglowState = object.getRgbUnderglowState ?? undefined;
    message.setRgbUnderglowState = (object.setRgbUnderglowState !== undefined && object.setRgbUnderglowState !== null)
      ? SetRgbUnderglowStateRequest.fromPartial(object.setRgbUnderglowState)
      : undefined;
    message.getBacklightState = object.getBacklightState ?? undefined;
    message.setBacklightState = (object.setBacklightState !== undefined && object.setBacklightState !== null)
      ? SetBacklightStateRequest.fromPartial(object.setBacklightState)
      : undefined;
    message.saveState = object.saveState ?? undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    getRgbUnderglowState: undefined,
    setRgbUnderglowState: undefined,
    getBacklightState: undefined,
    setBacklightState: undefined,
    saveState: undefined,
  };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getRgbUnderglowState !== undefined) {
      RgbUnderglowState.encode(message.getRgbUnderglowState, writer.uint32(10).fork()).ldelim();
    }
    if (message.setRgbUnderglowState !== undefined) {
      writer.uint32(16).bool(message.setRgbUnderglowState);
    }
    if (message.getBacklightState !== undefined) {
      BacklightState.encode(message.getBacklightState, writer.uint32(26).fork()).ldelim();
    }
    if (message.setBacklightState !== undefined) {
      writer.uint32(32).bool(message.setBacklightState);
    }
    if (message.saveState !== undefined) {
      writer.uint32(40).bool(message.saveState);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getRgbUnderglowState = RgbUnderglowState.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.setRgbUnderglowState = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.getBacklightState = BacklightState.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.setBacklightState = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.saveState = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getRgbUnderglowState: isSet(object.getRgbUnderglowState)
        ? RgbUnderglowState.fromJSON(object.getRgbUnderglowState)
        : undefined,
      setRgbUnderglowState: isSet(object.setRgbUnderglowState)
        ? globalThis.Boolean(object.setRgbUnderglowState)
        : undefined,
      getBacklightState: isSet(object.getBacklightState)
        ? BacklightState.fromJSON(object.getBacklightState)
        : undefined,
      setBacklightState: isSet(object.setBacklightState) ? globalThis.Boolean(object.setBacklightState) : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getRgbUnderglowState !== undefined) {
      obj.getRgbUnderglowState = RgbUnderglowState.toJSON(message.getRgbUnderglowState);
    }
    if (message.setRgbUnderglowState !== undefined) {
      obj.setRgbUnderglowState = message.setRgbUnderglowState;
    }
    if (message.getBacklightState !== undefined) {
      obj.getBacklightState = BacklightState.toJSON(message.getBacklightState);
    }
    if (message.setBacklightState !== undefined) {
      obj.setBacklightState = message.setBacklightState;
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getRgbUnderglowState = (object.getRgbUnderglowState !== undefined && object.getRgbUnderglowState !== null)
      ? RgbUnderglowState.fromPartial(object.getRgbUnderglowState)
      : undefined;
    message.setRgbUnderglowState = object.setRgbUnderglowState ?? undefined;
    message.getBacklightState = (object.getBacklightState !== undefined && object.getBacklightState !== null)
      ? BacklightState.fromPartial(object.getBacklightState)
      : undefined;
    message.setBacklightState = object.setBacklightState ?? undefined;
    message.saveState = object.saveState ?? undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { rgbUnderglowStateChanged: undefined, backlightStateChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.rgbUnderglowStateChanged !== undefined) {
      RgbUnderglowState.encode(message.rgbUnderglowStateChanged, writer.uint32(10).fork()).ldelim();
    }
    if (message.backlightStateChanged !== undefined) {
      BacklightState.encode(message.backlightStateChanged, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.rgbUnderglowStateChanged = RgbUnderglowState.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.backlightStateChanged = BacklightState.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      rgbUnderglowStateChanged: isSet(object.rgbUnderglowStateChanged)
        ? RgbUnderglowState.fromJSON(object.rgbUnderglowStateChanged)
        : undefined,
      backlightStateChanged: isSet(object.backlightStateChanged)
        ? BacklightState.fromJSON(object.backlightStateChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.rgbUnderglowStateChanged !== undefined) {
      obj.rgbUnderglowStateChanged = RgbUnderglowState.toJSON(message.rgbUnderglowStateChanged);
    }
    if (message.backlightStateChanged !== undefined) {
      obj.backlightStateChanged = BacklightState.toJSON(message.backlightStateChanged);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.rgbUnderglowStateChanged =
      (object.rgbUnderglowStateChanged !== undefined && object.rgbUnderglowStateChanged !== null)
        ? RgbUnderglowState.fromPartial(object.rgbUnderglowStateChanged)
        : undefined;
    message.backlightStateChanged =
      (object.backlightStateChanged !== undefined && object.backlightStateChanged !== null)
        ? BacklightState.fromPartial(object.backlightStateChanged)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
