// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.33.5
// source: lighting.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "zmk.lighting";

export interface HsbColor {
  /** Hue: 0-359 */
  h: number;
  /** Saturation: 0-100 */
  s: number;
  /** Brightness: 0-100 */
  b: number;
}

export interface RgbUnderglowState {
  on: boolean;
  color: HsbColor | undefined;
  effect: number;
  speed: number;
  effectCount: number;
  effectNames: string[];
}

export interface SetRgbUnderglowStateRequest {
  on?: boolean | undefined;
  color?: HsbColor | undefined;
  effect?: number | undefined;
  speed?: number | undefined;
}

export interface BacklightState {
  on: boolean;
  brightness: number;
}

export interface SetBacklightStateRequest {
  on?: boolean | undefined;
  brightness?: number | undefined;
}

export interface LayerLedBinding {
  keyPosition: number;
  /** 0xRRGGBB, 0 = transparent */
  color: number;
}

export interface LayerLedConfig {
  layerId: number;
  bindings: LayerLedBinding[];
}

export interface GetLayerLedColorsResponse {
  layers: LayerLedConfig[];
  keyCount: number;
  layerCount: number;
  enabled: boolean;
}

export interface SetLayerLedBindingRequest {
  layerId: number;
  keyPosition: number;
  /** 0xRRGGBB, 0 = transparent */
  color: number;
}

export interface CapsLockIndicatorState {
  enabled: boolean;
  /** 0xRRGGBB */
  offColor: number;
  /** 0xRRGGBB */
  onColor: number;
  keyPosition: number;
  /** 0xFF = any layer */
  layerId: number;
}

export interface SetCapsLockIndicatorRequest {
  enabled?: boolean | undefined;
  offColor?: number | undefined;
  onColor?: number | undefined;
  keyPosition?:
    | number
    | undefined;
  /** 0xFF = any layer */
  layerId?: number | undefined;
}

export interface ConnectionIndicatorState {
  enabled: boolean;
  /** 0xRRGGBB */
  usbColor: number;
  /** 0xRRGGBB */
  btColor: number;
  keyPosition: number;
  /** 0xFF = any layer */
  layerId: number;
}

export interface SetConnectionIndicatorRequest {
  enabled?: boolean | undefined;
  usbColor?: number | undefined;
  btColor?: number | undefined;
  keyPosition?: number | undefined;
  layerId?: number | undefined;
}

export interface SetLayerLedEnabledRequest {
  enabled: boolean;
}

export interface Request {
  getRgbUnderglowState?: boolean | undefined;
  setRgbUnderglowState?: SetRgbUnderglowStateRequest | undefined;
  getBacklightState?: boolean | undefined;
  setBacklightState?: SetBacklightStateRequest | undefined;
  saveState?: boolean | undefined;
  getLayerLedColors?: boolean | undefined;
  setLayerLedBinding?: SetLayerLedBindingRequest | undefined;
  getCapsLockIndicator?: boolean | undefined;
  setCapsLockIndicator?: SetCapsLockIndicatorRequest | undefined;
  saveLayerLedState?: boolean | undefined;
  setLayerLedEnabled?: SetLayerLedEnabledRequest | undefined;
  getConnectionIndicator?: boolean | undefined;
  setConnectionIndicator?: SetConnectionIndicatorRequest | undefined;
}

export interface Response {
  getRgbUnderglowState?: RgbUnderglowState | undefined;
  setRgbUnderglowState?: boolean | undefined;
  getBacklightState?: BacklightState | undefined;
  setBacklightState?: boolean | undefined;
  saveState?: boolean | undefined;
  getLayerLedColors?: GetLayerLedColorsResponse | undefined;
  setLayerLedBinding?: boolean | undefined;
  getCapsLockIndicator?: CapsLockIndicatorState | undefined;
  setCapsLockIndicator?: boolean | undefined;
  saveLayerLedState?: boolean | undefined;
  setLayerLedEnabled?: boolean | undefined;
  getConnectionIndicator?: ConnectionIndicatorState | undefined;
  setConnectionIndicator?: boolean | undefined;
}

export interface Notification {
  rgbUnderglowStateChanged?: RgbUnderglowState | undefined;
  backlightStateChanged?: BacklightState | undefined;
}

function createBaseHsbColor(): HsbColor {
  return { h: 0, s: 0, b: 0 };
}

export const HsbColor = {
  encode(message: HsbColor, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.h !== 0) {
      writer.uint32(8).uint32(message.h);
    }
    if (message.s !== 0) {
      writer.uint32(16).uint32(message.s);
    }
    if (message.b !== 0) {
      writer.uint32(24).uint32(message.b);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): HsbColor {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHsbColor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.h = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.s = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.b = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HsbColor {
    return {
      h: isSet(object.h) ? globalThis.Number(object.h) : 0,
      s: isSet(object.s) ? globalThis.Number(object.s) : 0,
      b: isSet(object.b) ? globalThis.Number(object.b) : 0,
    };
  },

  toJSON(message: HsbColor): unknown {
    const obj: any = {};
    if (message.h !== 0) {
      obj.h = Math.round(message.h);
    }
    if (message.s !== 0) {
      obj.s = Math.round(message.s);
    }
    if (message.b !== 0) {
      obj.b = Math.round(message.b);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HsbColor>, I>>(base?: I): HsbColor {
    return HsbColor.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HsbColor>, I>>(object: I): HsbColor {
    const message = createBaseHsbColor();
    message.h = object.h ?? 0;
    message.s = object.s ?? 0;
    message.b = object.b ?? 0;
    return message;
  },
};

function createBaseRgbUnderglowState(): RgbUnderglowState {
  return { on: false, color: undefined, effect: 0, speed: 0, effectCount: 0, effectNames: [] };
}

export const RgbUnderglowState = {
  encode(message: RgbUnderglowState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== false) {
      writer.uint32(8).bool(message.on);
    }
    if (message.color !== undefined) {
      HsbColor.encode(message.color, writer.uint32(18).fork()).ldelim();
    }
    if (message.effect !== 0) {
      writer.uint32(24).uint32(message.effect);
    }
    if (message.speed !== 0) {
      writer.uint32(32).uint32(message.speed);
    }
    if (message.effectCount !== 0) {
      writer.uint32(40).uint32(message.effectCount);
    }
    for (const v of message.effectNames) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RgbUnderglowState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRgbUnderglowState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.color = HsbColor.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.effect = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.speed = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.effectCount = reader.uint32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.effectNames.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RgbUnderglowState {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : false,
      color: isSet(object.color) ? HsbColor.fromJSON(object.color) : undefined,
      effect: isSet(object.effect) ? globalThis.Number(object.effect) : 0,
      speed: isSet(object.speed) ? globalThis.Number(object.speed) : 0,
      effectCount: isSet(object.effectCount) ? globalThis.Number(object.effectCount) : 0,
      effectNames: globalThis.Array.isArray(object?.effectNames)
        ? object.effectNames.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: RgbUnderglowState): unknown {
    const obj: any = {};
    if (message.on !== false) {
      obj.on = message.on;
    }
    if (message.color !== undefined) {
      obj.color = HsbColor.toJSON(message.color);
    }
    if (message.effect !== 0) {
      obj.effect = Math.round(message.effect);
    }
    if (message.speed !== 0) {
      obj.speed = Math.round(message.speed);
    }
    if (message.effectCount !== 0) {
      obj.effectCount = Math.round(message.effectCount);
    }
    if (message.effectNames?.length) {
      obj.effectNames = message.effectNames;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RgbUnderglowState>, I>>(base?: I): RgbUnderglowState {
    return RgbUnderglowState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RgbUnderglowState>, I>>(object: I): RgbUnderglowState {
    const message = createBaseRgbUnderglowState();
    message.on = object.on ?? false;
    message.color = (object.color !== undefined && object.color !== null)
      ? HsbColor.fromPartial(object.color)
      : undefined;
    message.effect = object.effect ?? 0;
    message.speed = object.speed ?? 0;
    message.effectCount = object.effectCount ?? 0;
    message.effectNames = object.effectNames?.map((e) => e) || [];
    return message;
  },
};

function createBaseSetRgbUnderglowStateRequest(): SetRgbUnderglowStateRequest {
  return { on: undefined, color: undefined, effect: undefined, speed: undefined };
}

export const SetRgbUnderglowStateRequest = {
  encode(message: SetRgbUnderglowStateRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== undefined) {
      writer.uint32(8).bool(message.on);
    }
    if (message.color !== undefined) {
      HsbColor.encode(message.color, writer.uint32(18).fork()).ldelim();
    }
    if (message.effect !== undefined) {
      writer.uint32(24).uint32(message.effect);
    }
    if (message.speed !== undefined) {
      writer.uint32(32).uint32(message.speed);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetRgbUnderglowStateRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetRgbUnderglowStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.color = HsbColor.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.effect = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.speed = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetRgbUnderglowStateRequest {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : undefined,
      color: isSet(object.color) ? HsbColor.fromJSON(object.color) : undefined,
      effect: isSet(object.effect) ? globalThis.Number(object.effect) : undefined,
      speed: isSet(object.speed) ? globalThis.Number(object.speed) : undefined,
    };
  },

  toJSON(message: SetRgbUnderglowStateRequest): unknown {
    const obj: any = {};
    if (message.on !== undefined) {
      obj.on = message.on;
    }
    if (message.color !== undefined) {
      obj.color = HsbColor.toJSON(message.color);
    }
    if (message.effect !== undefined) {
      obj.effect = Math.round(message.effect);
    }
    if (message.speed !== undefined) {
      obj.speed = Math.round(message.speed);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetRgbUnderglowStateRequest>, I>>(base?: I): SetRgbUnderglowStateRequest {
    return SetRgbUnderglowStateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetRgbUnderglowStateRequest>, I>>(object: I): SetRgbUnderglowStateRequest {
    const message = createBaseSetRgbUnderglowStateRequest();
    message.on = object.on ?? undefined;
    message.color = (object.color !== undefined && object.color !== null)
      ? HsbColor.fromPartial(object.color)
      : undefined;
    message.effect = object.effect ?? undefined;
    message.speed = object.speed ?? undefined;
    return message;
  },
};

function createBaseBacklightState(): BacklightState {
  return { on: false, brightness: 0 };
}

export const BacklightState = {
  encode(message: BacklightState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== false) {
      writer.uint32(8).bool(message.on);
    }
    if (message.brightness !== 0) {
      writer.uint32(16).uint32(message.brightness);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): BacklightState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBacklightState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.brightness = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BacklightState {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : false,
      brightness: isSet(object.brightness) ? globalThis.Number(object.brightness) : 0,
    };
  },

  toJSON(message: BacklightState): unknown {
    const obj: any = {};
    if (message.on !== false) {
      obj.on = message.on;
    }
    if (message.brightness !== 0) {
      obj.brightness = Math.round(message.brightness);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BacklightState>, I>>(base?: I): BacklightState {
    return BacklightState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BacklightState>, I>>(object: I): BacklightState {
    const message = createBaseBacklightState();
    message.on = object.on ?? false;
    message.brightness = object.brightness ?? 0;
    return message;
  },
};

function createBaseSetBacklightStateRequest(): SetBacklightStateRequest {
  return { on: undefined, brightness: undefined };
}

export const SetBacklightStateRequest = {
  encode(message: SetBacklightStateRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.on !== undefined) {
      writer.uint32(8).bool(message.on);
    }
    if (message.brightness !== undefined) {
      writer.uint32(16).uint32(message.brightness);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetBacklightStateRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetBacklightStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.on = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.brightness = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetBacklightStateRequest {
    return {
      on: isSet(object.on) ? globalThis.Boolean(object.on) : undefined,
      brightness: isSet(object.brightness) ? globalThis.Number(object.brightness) : undefined,
    };
  },

  toJSON(message: SetBacklightStateRequest): unknown {
    const obj: any = {};
    if (message.on !== undefined) {
      obj.on = message.on;
    }
    if (message.brightness !== undefined) {
      obj.brightness = Math.round(message.brightness);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetBacklightStateRequest>, I>>(base?: I): SetBacklightStateRequest {
    return SetBacklightStateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetBacklightStateRequest>, I>>(object: I): SetBacklightStateRequest {
    const message = createBaseSetBacklightStateRequest();
    message.on = object.on ?? undefined;
    message.brightness = object.brightness ?? undefined;
    return message;
  },
};

function createBaseLayerLedBinding(): LayerLedBinding {
  return { keyPosition: 0, color: 0 };
}

export const LayerLedBinding = {
  encode(message: LayerLedBinding, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.keyPosition !== 0) {
      writer.uint32(8).uint32(message.keyPosition);
    }
    if (message.color !== 0) {
      writer.uint32(16).uint32(message.color);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LayerLedBinding {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayerLedBinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.color = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LayerLedBinding {
    return {
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : 0,
      color: isSet(object.color) ? globalThis.Number(object.color) : 0,
    };
  },

  toJSON(message: LayerLedBinding): unknown {
    const obj: any = {};
    if (message.keyPosition !== 0) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.color !== 0) {
      obj.color = Math.round(message.color);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LayerLedBinding>, I>>(base?: I): LayerLedBinding {
    return LayerLedBinding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LayerLedBinding>, I>>(object: I): LayerLedBinding {
    const message = createBaseLayerLedBinding();
    message.keyPosition = object.keyPosition ?? 0;
    message.color = object.color ?? 0;
    return message;
  },
};

function createBaseLayerLedConfig(): LayerLedConfig {
  return { layerId: 0, bindings: [] };
}

export const LayerLedConfig = {
  encode(message: LayerLedConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.layerId !== 0) {
      writer.uint32(8).uint32(message.layerId);
    }
    for (const v of message.bindings) {
      LayerLedBinding.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LayerLedConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLayerLedConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.bindings.push(LayerLedBinding.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LayerLedConfig {
    return {
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
      bindings: globalThis.Array.isArray(object?.bindings)
        ? object.bindings.map((e: any) => LayerLedBinding.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LayerLedConfig): unknown {
    const obj: any = {};
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    if (message.bindings?.length) {
      obj.bindings = message.bindings.map((e) => LayerLedBinding.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LayerLedConfig>, I>>(base?: I): LayerLedConfig {
    return LayerLedConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LayerLedConfig>, I>>(object: I): LayerLedConfig {
    const message = createBaseLayerLedConfig();
    message.layerId = object.layerId ?? 0;
    message.bindings = object.bindings?.map((e) => LayerLedBinding.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetLayerLedColorsResponse(): GetLayerLedColorsResponse {
  return { layers: [], keyCount: 0, layerCount: 0, enabled: false };
}

export const GetLayerLedColorsResponse = {
  encode(message: GetLayerLedColorsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.layers) {
      LayerLedConfig.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.keyCount !== 0) {
      writer.uint32(16).uint32(message.keyCount);
    }
    if (message.layerCount !== 0) {
      writer.uint32(24).uint32(message.layerCount);
    }
    if (message.enabled !== false) {
      writer.uint32(32).bool(message.enabled);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetLayerLedColorsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLayerLedColorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.layers.push(LayerLedConfig.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.keyCount = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.layerCount = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.enabled = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLayerLedColorsResponse {
    return {
      layers: globalThis.Array.isArray(object?.layers) ? object.layers.map((e: any) => LayerLedConfig.fromJSON(e)) : [],
      keyCount: isSet(object.keyCount) ? globalThis.Number(object.keyCount) : 0,
      layerCount: isSet(object.layerCount) ? globalThis.Number(object.layerCount) : 0,
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: GetLayerLedColorsResponse): unknown {
    const obj: any = {};
    if (message.layers?.length) {
      obj.layers = message.layers.map((e) => LayerLedConfig.toJSON(e));
    }
    if (message.keyCount !== 0) {
      obj.keyCount = Math.round(message.keyCount);
    }
    if (message.layerCount !== 0) {
      obj.layerCount = Math.round(message.layerCount);
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLayerLedColorsResponse>, I>>(base?: I): GetLayerLedColorsResponse {
    return GetLayerLedColorsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLayerLedColorsResponse>, I>>(object: I): GetLayerLedColorsResponse {
    const message = createBaseGetLayerLedColorsResponse();
    message.layers = object.layers?.map((e) => LayerLedConfig.fromPartial(e)) || [];
    message.keyCount = object.keyCount ?? 0;
    message.layerCount = object.layerCount ?? 0;
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseSetLayerLedBindingRequest(): SetLayerLedBindingRequest {
  return { layerId: 0, keyPosition: 0, color: 0 };
}

export const SetLayerLedBindingRequest = {
  encode(message: SetLayerLedBindingRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.layerId !== 0) {
      writer.uint32(8).uint32(message.layerId);
    }
    if (message.keyPosition !== 0) {
      writer.uint32(16).uint32(message.keyPosition);
    }
    if (message.color !== 0) {
      writer.uint32(24).uint32(message.color);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetLayerLedBindingRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerLedBindingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.color = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetLayerLedBindingRequest {
    return {
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : 0,
      color: isSet(object.color) ? globalThis.Number(object.color) : 0,
    };
  },

  toJSON(message: SetLayerLedBindingRequest): unknown {
    const obj: any = {};
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    if (message.keyPosition !== 0) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.color !== 0) {
      obj.color = Math.round(message.color);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetLayerLedBindingRequest>, I>>(base?: I): SetLayerLedBindingRequest {
    return SetLayerLedBindingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetLayerLedBindingRequest>, I>>(object: I): SetLayerLedBindingRequest {
    const message = createBaseSetLayerLedBindingRequest();
    message.layerId = object.layerId ?? 0;
    message.keyPosition = object.keyPosition ?? 0;
    message.color = object.color ?? 0;
    return message;
  },
};

function createBaseCapsLockIndicatorState(): CapsLockIndicatorState {
  return { enabled: false, offColor: 0, onColor: 0, keyPosition: 0, layerId: 0 };
}

export const CapsLockIndicatorState = {
  encode(message: CapsLockIndicatorState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.offColor !== 0) {
      writer.uint32(16).uint32(message.offColor);
    }
    if (message.onColor !== 0) {
      writer.uint32(24).uint32(message.onColor);
    }
    if (message.keyPosition !== 0) {
      writer.uint32(32).uint32(message.keyPosition);
    }
    if (message.layerId !== 0) {
      writer.uint32(40).uint32(message.layerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CapsLockIndicatorState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCapsLockIndicatorState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.offColor = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.onColor = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CapsLockIndicatorState {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      offColor: isSet(object.offColor) ? globalThis.Number(object.offColor) : 0,
      onColor: isSet(object.onColor) ? globalThis.Number(object.onColor) : 0,
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : 0,
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
    };
  },

  toJSON(message: CapsLockIndicatorState): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.offColor !== 0) {
      obj.offColor = Math.round(message.offColor);
    }
    if (message.onColor !== 0) {
      obj.onColor = Math.round(message.onColor);
    }
    if (message.keyPosition !== 0) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CapsLockIndicatorState>, I>>(base?: I): CapsLockIndicatorState {
    return CapsLockIndicatorState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CapsLockIndicatorState>, I>>(object: I): CapsLockIndicatorState {
    const message = createBaseCapsLockIndicatorState();
    message.enabled = object.enabled ?? false;
    message.offColor = object.offColor ?? 0;
    message.onColor = object.onColor ?? 0;
    message.keyPosition = object.keyPosition ?? 0;
    message.layerId = object.layerId ?? 0;
    return message;
  },
};

function createBaseSetCapsLockIndicatorRequest(): SetCapsLockIndicatorRequest {
  return { enabled: undefined, offColor: undefined, onColor: undefined, keyPosition: undefined, layerId: undefined };
}

export const SetCapsLockIndicatorRequest = {
  encode(message: SetCapsLockIndicatorRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== undefined) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.offColor !== undefined) {
      writer.uint32(16).uint32(message.offColor);
    }
    if (message.onColor !== undefined) {
      writer.uint32(24).uint32(message.onColor);
    }
    if (message.keyPosition !== undefined) {
      writer.uint32(32).uint32(message.keyPosition);
    }
    if (message.layerId !== undefined) {
      writer.uint32(40).uint32(message.layerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetCapsLockIndicatorRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetCapsLockIndicatorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.offColor = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.onColor = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetCapsLockIndicatorRequest {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : undefined,
      offColor: isSet(object.offColor) ? globalThis.Number(object.offColor) : undefined,
      onColor: isSet(object.onColor) ? globalThis.Number(object.onColor) : undefined,
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : undefined,
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : undefined,
    };
  },

  toJSON(message: SetCapsLockIndicatorRequest): unknown {
    const obj: any = {};
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.offColor !== undefined) {
      obj.offColor = Math.round(message.offColor);
    }
    if (message.onColor !== undefined) {
      obj.onColor = Math.round(message.onColor);
    }
    if (message.keyPosition !== undefined) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.layerId !== undefined) {
      obj.layerId = Math.round(message.layerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetCapsLockIndicatorRequest>, I>>(base?: I): SetCapsLockIndicatorRequest {
    return SetCapsLockIndicatorRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetCapsLockIndicatorRequest>, I>>(object: I): SetCapsLockIndicatorRequest {
    const message = createBaseSetCapsLockIndicatorRequest();
    message.enabled = object.enabled ?? undefined;
    message.offColor = object.offColor ?? undefined;
    message.onColor = object.onColor ?? undefined;
    message.keyPosition = object.keyPosition ?? undefined;
    message.layerId = object.layerId ?? undefined;
    return message;
  },
};

function createBaseConnectionIndicatorState(): ConnectionIndicatorState {
  return { enabled: false, usbColor: 0, btColor: 0, keyPosition: 0, layerId: 0 };
}

export const ConnectionIndicatorState = {
  encode(message: ConnectionIndicatorState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.usbColor !== 0) {
      writer.uint32(16).uint32(message.usbColor);
    }
    if (message.btColor !== 0) {
      writer.uint32(24).uint32(message.btColor);
    }
    if (message.keyPosition !== 0) {
      writer.uint32(32).uint32(message.keyPosition);
    }
    if (message.layerId !== 0) {
      writer.uint32(40).uint32(message.layerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ConnectionIndicatorState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectionIndicatorState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.usbColor = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.btColor = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectionIndicatorState {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      usbColor: isSet(object.usbColor) ? globalThis.Number(object.usbColor) : 0,
      btColor: isSet(object.btColor) ? globalThis.Number(object.btColor) : 0,
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : 0,
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : 0,
    };
  },

  toJSON(message: ConnectionIndicatorState): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.usbColor !== 0) {
      obj.usbColor = Math.round(message.usbColor);
    }
    if (message.btColor !== 0) {
      obj.btColor = Math.round(message.btColor);
    }
    if (message.keyPosition !== 0) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.layerId !== 0) {
      obj.layerId = Math.round(message.layerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectionIndicatorState>, I>>(base?: I): ConnectionIndicatorState {
    return ConnectionIndicatorState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectionIndicatorState>, I>>(object: I): ConnectionIndicatorState {
    const message = createBaseConnectionIndicatorState();
    message.enabled = object.enabled ?? false;
    message.usbColor = object.usbColor ?? 0;
    message.btColor = object.btColor ?? 0;
    message.keyPosition = object.keyPosition ?? 0;
    message.layerId = object.layerId ?? 0;
    return message;
  },
};

function createBaseSetConnectionIndicatorRequest(): SetConnectionIndicatorRequest {
  return { enabled: undefined, usbColor: undefined, btColor: undefined, keyPosition: undefined, layerId: undefined };
}

export const SetConnectionIndicatorRequest = {
  encode(message: SetConnectionIndicatorRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== undefined) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.usbColor !== undefined) {
      writer.uint32(16).uint32(message.usbColor);
    }
    if (message.btColor !== undefined) {
      writer.uint32(24).uint32(message.btColor);
    }
    if (message.keyPosition !== undefined) {
      writer.uint32(32).uint32(message.keyPosition);
    }
    if (message.layerId !== undefined) {
      writer.uint32(40).uint32(message.layerId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetConnectionIndicatorRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConnectionIndicatorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.usbColor = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.btColor = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.keyPosition = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.layerId = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetConnectionIndicatorRequest {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : undefined,
      usbColor: isSet(object.usbColor) ? globalThis.Number(object.usbColor) : undefined,
      btColor: isSet(object.btColor) ? globalThis.Number(object.btColor) : undefined,
      keyPosition: isSet(object.keyPosition) ? globalThis.Number(object.keyPosition) : undefined,
      layerId: isSet(object.layerId) ? globalThis.Number(object.layerId) : undefined,
    };
  },

  toJSON(message: SetConnectionIndicatorRequest): unknown {
    const obj: any = {};
    if (message.enabled !== undefined) {
      obj.enabled = message.enabled;
    }
    if (message.usbColor !== undefined) {
      obj.usbColor = Math.round(message.usbColor);
    }
    if (message.btColor !== undefined) {
      obj.btColor = Math.round(message.btColor);
    }
    if (message.keyPosition !== undefined) {
      obj.keyPosition = Math.round(message.keyPosition);
    }
    if (message.layerId !== undefined) {
      obj.layerId = Math.round(message.layerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetConnectionIndicatorRequest>, I>>(base?: I): SetConnectionIndicatorRequest {
    return SetConnectionIndicatorRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetConnectionIndicatorRequest>, I>>(
    object: I,
  ): SetConnectionIndicatorRequest {
    const message = createBaseSetConnectionIndicatorRequest();
    message.enabled = object.enabled ?? undefined;
    message.usbColor = object.usbColor ?? undefined;
    message.btColor = object.btColor ?? undefined;
    message.keyPosition = object.keyPosition ?? undefined;
    message.layerId = object.layerId ?? undefined;
    return message;
  },
};

function createBaseSetLayerLedEnabledRequest(): SetLayerLedEnabledRequest {
  return { enabled: false };
}

export const SetLayerLedEnabledRequest = {
  encode(message: SetLayerLedEnabledRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SetLayerLedEnabledRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetLayerLedEnabledRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetLayerLedEnabledRequest {
    return { enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false };
  },

  toJSON(message: SetLayerLedEnabledRequest): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetLayerLedEnabledRequest>, I>>(base?: I): SetLayerLedEnabledRequest {
    return SetLayerLedEnabledRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetLayerLedEnabledRequest>, I>>(object: I): SetLayerLedEnabledRequest {
    const message = createBaseSetLayerLedEnabledRequest();
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseRequest(): Request {
  return {
    getRgbUnderglowState: undefined,
    setRgbUnderglowState: undefined,
    getBacklightState: undefined,
    setBacklightState: undefined,
    saveState: undefined,
    getLayerLedColors: undefined,
    setLayerLedBinding: undefined,
    getCapsLockIndicator: undefined,
    setCapsLockIndicator: undefined,
    saveLayerLedState: undefined,
    setLayerLedEnabled: undefined,
    getConnectionIndicator: undefined,
    setConnectionIndicator: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getRgbUnderglowState !== undefined) {
      writer.uint32(8).bool(message.getRgbUnderglowState);
    }
    if (message.setRgbUnderglowState !== undefined) {
      SetRgbUnderglowStateRequest.encode(message.setRgbUnderglowState, writer.uint32(18).fork()).ldelim();
    }
    if (message.getBacklightState !== undefined) {
      writer.uint32(24).bool(message.getBacklightState);
    }
    if (message.setBacklightState !== undefined) {
      SetBacklightStateRequest.encode(message.setBacklightState, writer.uint32(34).fork()).ldelim();
    }
    if (message.saveState !== undefined) {
      writer.uint32(40).bool(message.saveState);
    }
    if (message.getLayerLedColors !== undefined) {
      writer.uint32(48).bool(message.getLayerLedColors);
    }
    if (message.setLayerLedBinding !== undefined) {
      SetLayerLedBindingRequest.encode(message.setLayerLedBinding, writer.uint32(58).fork()).ldelim();
    }
    if (message.getCapsLockIndicator !== undefined) {
      writer.uint32(64).bool(message.getCapsLockIndicator);
    }
    if (message.setCapsLockIndicator !== undefined) {
      SetCapsLockIndicatorRequest.encode(message.setCapsLockIndicator, writer.uint32(74).fork()).ldelim();
    }
    if (message.saveLayerLedState !== undefined) {
      writer.uint32(80).bool(message.saveLayerLedState);
    }
    if (message.setLayerLedEnabled !== undefined) {
      SetLayerLedEnabledRequest.encode(message.setLayerLedEnabled, writer.uint32(90).fork()).ldelim();
    }
    if (message.getConnectionIndicator !== undefined) {
      writer.uint32(96).bool(message.getConnectionIndicator);
    }
    if (message.setConnectionIndicator !== undefined) {
      SetConnectionIndicatorRequest.encode(message.setConnectionIndicator, writer.uint32(106).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getRgbUnderglowState = reader.bool();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.setRgbUnderglowState = SetRgbUnderglowStateRequest.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.getBacklightState = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.setBacklightState = SetBacklightStateRequest.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.saveState = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.getLayerLedColors = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.setLayerLedBinding = SetLayerLedBindingRequest.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.getCapsLockIndicator = reader.bool();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.setCapsLockIndicator = SetCapsLockIndicatorRequest.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.saveLayerLedState = reader.bool();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.setLayerLedEnabled = SetLayerLedEnabledRequest.decode(reader, reader.uint32());
          continue;
        case 12:
          if (tag !== 96) {
            break;
          }

          message.getConnectionIndicator = reader.bool();
          continue;
        case 13:
          if (tag !== 106) {
            break;
          }

          message.setConnectionIndicator = SetConnectionIndicatorRequest.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getRgbUnderglowState: isSet(object.getRgbUnderglowState)
        ? globalThis.Boolean(object.getRgbUnderglowState)
        : undefined,
      setRgbUnderglowState: isSet(object.setRgbUnderglowState)
        ? SetRgbUnderglowStateRequest.fromJSON(object.setRgbUnderglowState)
        : undefined,
      getBacklightState: isSet(object.getBacklightState) ? globalThis.Boolean(object.getBacklightState) : undefined,
      setBacklightState: isSet(object.setBacklightState)
        ? SetBacklightStateRequest.fromJSON(object.setBacklightState)
        : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
      getLayerLedColors: isSet(object.getLayerLedColors) ? globalThis.Boolean(object.getLayerLedColors) : undefined,
      setLayerLedBinding: isSet(object.setLayerLedBinding)
        ? SetLayerLedBindingRequest.fromJSON(object.setLayerLedBinding)
        : undefined,
      getCapsLockIndicator: isSet(object.getCapsLockIndicator)
        ? globalThis.Boolean(object.getCapsLockIndicator)
        : undefined,
      setCapsLockIndicator: isSet(object.setCapsLockIndicator)
        ? SetCapsLockIndicatorRequest.fromJSON(object.setCapsLockIndicator)
        : undefined,
      saveLayerLedState: isSet(object.saveLayerLedState) ? globalThis.Boolean(object.saveLayerLedState) : undefined,
      setLayerLedEnabled: isSet(object.setLayerLedEnabled)
        ? SetLayerLedEnabledRequest.fromJSON(object.setLayerLedEnabled)
        : undefined,
      getConnectionIndicator: isSet(object.getConnectionIndicator)
        ? globalThis.Boolean(object.getConnectionIndicator)
        : undefined,
      setConnectionIndicator: isSet(object.setConnectionIndicator)
        ? SetConnectionIndicatorRequest.fromJSON(object.setConnectionIndicator)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getRgbUnderglowState !== undefined) {
      obj.getRgbUnderglowState = message.getRgbUnderglowState;
    }
    if (message.setRgbUnderglowState !== undefined) {
      obj.setRgbUnderglowState = SetRgbUnderglowStateRequest.toJSON(message.setRgbUnderglowState);
    }
    if (message.getBacklightState !== undefined) {
      obj.getBacklightState = message.getBacklightState;
    }
    if (message.setBacklightState !== undefined) {
      obj.setBacklightState = SetBacklightStateRequest.toJSON(message.setBacklightState);
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    if (message.getLayerLedColors !== undefined) {
      obj.getLayerLedColors = message.getLayerLedColors;
    }
    if (message.setLayerLedBinding !== undefined) {
      obj.setLayerLedBinding = SetLayerLedBindingRequest.toJSON(message.setLayerLedBinding);
    }
    if (message.getCapsLockIndicator !== undefined) {
      obj.getCapsLockIndicator = message.getCapsLockIndicator;
    }
    if (message.setCapsLockIndicator !== undefined) {
      obj.setCapsLockIndicator = SetCapsLockIndicatorRequest.toJSON(message.setCapsLockIndicator);
    }
    if (message.saveLayerLedState !== undefined) {
      obj.saveLayerLedState = message.saveLayerLedState;
    }
    if (message.setLayerLedEnabled !== undefined) {
      obj.setLayerLedEnabled = SetLayerLedEnabledRequest.toJSON(message.setLayerLedEnabled);
    }
    if (message.getConnectionIndicator !== undefined) {
      obj.getConnectionIndicator = message.getConnectionIndicator;
    }
    if (message.setConnectionIndicator !== undefined) {
      obj.setConnectionIndicator = SetConnectionIndicatorRequest.toJSON(message.setConnectionIndicator);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getRgbUnderglowState = object.getRgbUnderglowState ?? undefined;
    message.setRgbUnderglowState = (object.setRgbUnderglowState !== undefined && object.setRgbUnderglowState !== null)
      ? SetRgbUnderglowStateRequest.fromPartial(object.setRgbUnderglowState)
      : undefined;
    message.getBacklightState = object.getBacklightState ?? undefined;
    message.setBacklightState = (object.setBacklightState !== undefined && object.setBacklightState !== null)
      ? SetBacklightStateRequest.fromPartial(object.setBacklightState)
      : undefined;
    message.saveState = object.saveState ?? undefined;
    message.getLayerLedColors = object.getLayerLedColors ?? undefined;
    message.setLayerLedBinding = (object.setLayerLedBinding !== undefined && object.setLayerLedBinding !== null)
      ? SetLayerLedBindingRequest.fromPartial(object.setLayerLedBinding)
      : undefined;
    message.getCapsLockIndicator = object.getCapsLockIndicator ?? undefined;
    message.setCapsLockIndicator = (object.setCapsLockIndicator !== undefined && object.setCapsLockIndicator !== null)
      ? SetCapsLockIndicatorRequest.fromPartial(object.setCapsLockIndicator)
      : undefined;
    message.saveLayerLedState = object.saveLayerLedState ?? undefined;
    message.setLayerLedEnabled = (object.setLayerLedEnabled !== undefined && object.setLayerLedEnabled !== null)
      ? SetLayerLedEnabledRequest.fromPartial(object.setLayerLedEnabled)
      : undefined;
    message.getConnectionIndicator = object.getConnectionIndicator ?? undefined;
    message.setConnectionIndicator =
      (object.setConnectionIndicator !== undefined && object.setConnectionIndicator !== null)
        ? SetConnectionIndicatorRequest.fromPartial(object.setConnectionIndicator)
        : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    getRgbUnderglowState: undefined,
    setRgbUnderglowState: undefined,
    getBacklightState: undefined,
    setBacklightState: undefined,
    saveState: undefined,
    getLayerLedColors: undefined,
    setLayerLedBinding: undefined,
    getCapsLockIndicator: undefined,
    setCapsLockIndicator: undefined,
    saveLayerLedState: undefined,
    setLayerLedEnabled: undefined,
    getConnectionIndicator: undefined,
    setConnectionIndicator: undefined,
  };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getRgbUnderglowState !== undefined) {
      RgbUnderglowState.encode(message.getRgbUnderglowState, writer.uint32(10).fork()).ldelim();
    }
    if (message.setRgbUnderglowState !== undefined) {
      writer.uint32(16).bool(message.setRgbUnderglowState);
    }
    if (message.getBacklightState !== undefined) {
      BacklightState.encode(message.getBacklightState, writer.uint32(26).fork()).ldelim();
    }
    if (message.setBacklightState !== undefined) {
      writer.uint32(32).bool(message.setBacklightState);
    }
    if (message.saveState !== undefined) {
      writer.uint32(40).bool(message.saveState);
    }
    if (message.getLayerLedColors !== undefined) {
      GetLayerLedColorsResponse.encode(message.getLayerLedColors, writer.uint32(50).fork()).ldelim();
    }
    if (message.setLayerLedBinding !== undefined) {
      writer.uint32(56).bool(message.setLayerLedBinding);
    }
    if (message.getCapsLockIndicator !== undefined) {
      CapsLockIndicatorState.encode(message.getCapsLockIndicator, writer.uint32(66).fork()).ldelim();
    }
    if (message.setCapsLockIndicator !== undefined) {
      writer.uint32(72).bool(message.setCapsLockIndicator);
    }
    if (message.saveLayerLedState !== undefined) {
      writer.uint32(80).bool(message.saveLayerLedState);
    }
    if (message.setLayerLedEnabled !== undefined) {
      writer.uint32(88).bool(message.setLayerLedEnabled);
    }
    if (message.getConnectionIndicator !== undefined) {
      ConnectionIndicatorState.encode(message.getConnectionIndicator, writer.uint32(98).fork()).ldelim();
    }
    if (message.setConnectionIndicator !== undefined) {
      writer.uint32(104).bool(message.setConnectionIndicator);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.getRgbUnderglowState = RgbUnderglowState.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.setRgbUnderglowState = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.getBacklightState = BacklightState.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.setBacklightState = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.saveState = reader.bool();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.getLayerLedColors = GetLayerLedColorsResponse.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.setLayerLedBinding = reader.bool();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.getCapsLockIndicator = CapsLockIndicatorState.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.setCapsLockIndicator = reader.bool();
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.saveLayerLedState = reader.bool();
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.setLayerLedEnabled = reader.bool();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.getConnectionIndicator = ConnectionIndicatorState.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.setConnectionIndicator = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      getRgbUnderglowState: isSet(object.getRgbUnderglowState)
        ? RgbUnderglowState.fromJSON(object.getRgbUnderglowState)
        : undefined,
      setRgbUnderglowState: isSet(object.setRgbUnderglowState)
        ? globalThis.Boolean(object.setRgbUnderglowState)
        : undefined,
      getBacklightState: isSet(object.getBacklightState)
        ? BacklightState.fromJSON(object.getBacklightState)
        : undefined,
      setBacklightState: isSet(object.setBacklightState) ? globalThis.Boolean(object.setBacklightState) : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
      getLayerLedColors: isSet(object.getLayerLedColors)
        ? GetLayerLedColorsResponse.fromJSON(object.getLayerLedColors)
        : undefined,
      setLayerLedBinding: isSet(object.setLayerLedBinding) ? globalThis.Boolean(object.setLayerLedBinding) : undefined,
      getCapsLockIndicator: isSet(object.getCapsLockIndicator)
        ? CapsLockIndicatorState.fromJSON(object.getCapsLockIndicator)
        : undefined,
      setCapsLockIndicator: isSet(object.setCapsLockIndicator)
        ? globalThis.Boolean(object.setCapsLockIndicator)
        : undefined,
      saveLayerLedState: isSet(object.saveLayerLedState) ? globalThis.Boolean(object.saveLayerLedState) : undefined,
      setLayerLedEnabled: isSet(object.setLayerLedEnabled) ? globalThis.Boolean(object.setLayerLedEnabled) : undefined,
      getConnectionIndicator: isSet(object.getConnectionIndicator)
        ? ConnectionIndicatorState.fromJSON(object.getConnectionIndicator)
        : undefined,
      setConnectionIndicator: isSet(object.setConnectionIndicator)
        ? globalThis.Boolean(object.setConnectionIndicator)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.getRgbUnderglowState !== undefined) {
      obj.getRgbUnderglowState = RgbUnderglowState.toJSON(message.getRgbUnderglowState);
    }
    if (message.setRgbUnderglowState !== undefined) {
      obj.setRgbUnderglowState = message.setRgbUnderglowState;
    }
    if (message.getBacklightState !== undefined) {
      obj.getBacklightState = BacklightState.toJSON(message.getBacklightState);
    }
    if (message.setBacklightState !== undefined) {
      obj.setBacklightState = message.setBacklightState;
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    if (message.getLayerLedColors !== undefined) {
      obj.getLayerLedColors = GetLayerLedColorsResponse.toJSON(message.getLayerLedColors);
    }
    if (message.setLayerLedBinding !== undefined) {
      obj.setLayerLedBinding = message.setLayerLedBinding;
    }
    if (message.getCapsLockIndicator !== undefined) {
      obj.getCapsLockIndicator = CapsLockIndicatorState.toJSON(message.getCapsLockIndicator);
    }
    if (message.setCapsLockIndicator !== undefined) {
      obj.setCapsLockIndicator = message.setCapsLockIndicator;
    }
    if (message.saveLayerLedState !== undefined) {
      obj.saveLayerLedState = message.saveLayerLedState;
    }
    if (message.setLayerLedEnabled !== undefined) {
      obj.setLayerLedEnabled = message.setLayerLedEnabled;
    }
    if (message.getConnectionIndicator !== undefined) {
      obj.getConnectionIndicator = ConnectionIndicatorState.toJSON(message.getConnectionIndicator);
    }
    if (message.setConnectionIndicator !== undefined) {
      obj.setConnectionIndicator = message.setConnectionIndicator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.getRgbUnderglowState = (object.getRgbUnderglowState !== undefined && object.getRgbUnderglowState !== null)
      ? RgbUnderglowState.fromPartial(object.getRgbUnderglowState)
      : undefined;
    message.setRgbUnderglowState = object.setRgbUnderglowState ?? undefined;
    message.getBacklightState = (object.getBacklightState !== undefined && object.getBacklightState !== null)
      ? BacklightState.fromPartial(object.getBacklightState)
      : undefined;
    message.setBacklightState = object.setBacklightState ?? undefined;
    message.saveState = object.saveState ?? undefined;
    message.getLayerLedColors = (object.getLayerLedColors !== undefined && object.getLayerLedColors !== null)
      ? GetLayerLedColorsResponse.fromPartial(object.getLayerLedColors)
      : undefined;
    message.setLayerLedBinding = object.setLayerLedBinding ?? undefined;
    message.getCapsLockIndicator = (object.getCapsLockIndicator !== undefined && object.getCapsLockIndicator !== null)
      ? CapsLockIndicatorState.fromPartial(object.getCapsLockIndicator)
      : undefined;
    message.setCapsLockIndicator = object.setCapsLockIndicator ?? undefined;
    message.saveLayerLedState = object.saveLayerLedState ?? undefined;
    message.setLayerLedEnabled = object.setLayerLedEnabled ?? undefined;
    message.getConnectionIndicator =
      (object.getConnectionIndicator !== undefined && object.getConnectionIndicator !== null)
        ? ConnectionIndicatorState.fromPartial(object.getConnectionIndicator)
        : undefined;
    message.setConnectionIndicator = object.setConnectionIndicator ?? undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { rgbUnderglowStateChanged: undefined, backlightStateChanged: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.rgbUnderglowStateChanged !== undefined) {
      RgbUnderglowState.encode(message.rgbUnderglowStateChanged, writer.uint32(10).fork()).ldelim();
    }
    if (message.backlightStateChanged !== undefined) {
      BacklightState.encode(message.backlightStateChanged, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.rgbUnderglowStateChanged = RgbUnderglowState.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.backlightStateChanged = BacklightState.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return {
      rgbUnderglowStateChanged: isSet(object.rgbUnderglowStateChanged)
        ? RgbUnderglowState.fromJSON(object.rgbUnderglowStateChanged)
        : undefined,
      backlightStateChanged: isSet(object.backlightStateChanged)
        ? BacklightState.fromJSON(object.backlightStateChanged)
        : undefined,
    };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.rgbUnderglowStateChanged !== undefined) {
      obj.rgbUnderglowStateChanged = RgbUnderglowState.toJSON(message.rgbUnderglowStateChanged);
    }
    if (message.backlightStateChanged !== undefined) {
      obj.backlightStateChanged = BacklightState.toJSON(message.backlightStateChanged);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.rgbUnderglowStateChanged =
      (object.rgbUnderglowStateChanged !== undefined && object.rgbUnderglowStateChanged !== null)
        ? RgbUnderglowState.fromPartial(object.rgbUnderglowStateChanged)
        : undefined;
    message.backlightStateChanged =
      (object.backlightStateChanged !== undefined && object.backlightStateChanged !== null)
        ? BacklightState.fromPartial(object.backlightStateChanged)
        : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
