// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v6.33.5
// source: motion.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { BehaviorBinding } from "./keymap";

export const protobufPackage = "zmk.motion";

export enum Orientation {
  ORIENTATION_UNKNOWN = 0,
  ORIENTATION_FLAT_UP = 1,
  ORIENTATION_FLAT_DOWN = 2,
  ORIENTATION_TILTED = 3,
  UNRECOGNIZED = -1,
}

export function orientationFromJSON(object: any): Orientation {
  switch (object) {
    case 0:
    case "ORIENTATION_UNKNOWN":
      return Orientation.ORIENTATION_UNKNOWN;
    case 1:
    case "ORIENTATION_FLAT_UP":
      return Orientation.ORIENTATION_FLAT_UP;
    case 2:
    case "ORIENTATION_FLAT_DOWN":
      return Orientation.ORIENTATION_FLAT_DOWN;
    case 3:
    case "ORIENTATION_TILTED":
      return Orientation.ORIENTATION_TILTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Orientation.UNRECOGNIZED;
  }
}

export function orientationToJSON(object: Orientation): string {
  switch (object) {
    case Orientation.ORIENTATION_UNKNOWN:
      return "ORIENTATION_UNKNOWN";
    case Orientation.ORIENTATION_FLAT_UP:
      return "ORIENTATION_FLAT_UP";
    case Orientation.ORIENTATION_FLAT_DOWN:
      return "ORIENTATION_FLAT_DOWN";
    case Orientation.ORIENTATION_TILTED:
      return "ORIENTATION_TILTED";
    case Orientation.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Request {
  getCapabilities?: boolean | undefined;
  getTapConfig?: boolean | undefined;
  setTapConfig?: TapConfig | undefined;
  getCarryConfig?: boolean | undefined;
  setCarryConfig?: CarryConfig | undefined;
  saveState?: boolean | undefined;
  setLiveStream?: boolean | undefined;
  getStillWakeConfig?: boolean | undefined;
  setStillWakeConfig?: StillWakeConfig | undefined;
}

export interface Response {
  capabilities?: Capabilities | undefined;
  tapConfig?: TapConfig | undefined;
  setTapConfig?: boolean | undefined;
  carryConfig?: CarryConfig | undefined;
  setCarryConfig?: boolean | undefined;
  saveState?: boolean | undefined;
  setLiveStream?: boolean | undefined;
  stillWakeConfig?: StillWakeConfig | undefined;
  setStillWakeConfig?: boolean | undefined;
}

export interface Capabilities {
  /** "lis2dh12" */
  sensor: string;
  supportsTap: boolean;
  supportsDoubleTap: boolean;
  supportsCarry: boolean;
  thresholdMax: number;
  supportsStillWake: boolean;
}

/**
 * Any binding may be omitted. When a single and its double are both set on
 * the same side, the single fires one window late so the double can supersede.
 */
export interface TapConfig {
  enabled: boolean;
  /** CLICK_THS, shared by all taps */
  threshold: number;
  /** TIME_LIMIT */
  timeLimitMs: number;
  /** TIME_LATENCY */
  latencyMs: number;
  /** TIME_WINDOW — second-tap / arbitration window */
  windowMs: number;
  leftSingleBinding: BehaviorBinding | undefined;
  leftDoubleBinding: BehaviorBinding | undefined;
  rightSingleBinding: BehaviorBinding | undefined;
  rightDoubleBinding:
    | BehaviorBinding
    | undefined;
  /** 0 = all layers */
  layerMask: number;
}

export interface CarryConfig {
  enabled: boolean;
  /** INT_THS for the any-motion interrupt */
  motionThreshold: number;
  /** walking must persist this long before sleep */
  motionDurationMs: number;
}

/**
 * Keeps the keyboard awake once it has been set down: after a motion wake-up,
 * the sensor must stay still for this long or the keyboard goes straight back
 * to sleep. Settling is judged by the same any-motion streak falling silent.
 */
export interface StillWakeConfig {
  enabled: boolean;
  /** stillness required to stay awake */
  settleDurationMs: number;
}

export interface LiveState {
  /**
   * Peak acceleration within the push period, in the same raw counts the
   * threshold fields use, so a threshold marker can be drawn on the meter.
   */
  magnitude: number;
  orientation: Orientation;
  /** walking detected, sleep imminent */
  carryActive: boolean;
  tapDetected: boolean;
  /** raw CLICK_SRC of the last tap */
  lastClickSrc: number;
}

export interface Notification {
  liveState?: LiveState | undefined;
}

function createBaseRequest(): Request {
  return {
    getCapabilities: undefined,
    getTapConfig: undefined,
    setTapConfig: undefined,
    getCarryConfig: undefined,
    setCarryConfig: undefined,
    saveState: undefined,
    setLiveStream: undefined,
    getStillWakeConfig: undefined,
    setStillWakeConfig: undefined,
  };
}

export const Request = {
  encode(message: Request, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.getCapabilities !== undefined) {
      writer.uint32(8).bool(message.getCapabilities);
    }
    if (message.getTapConfig !== undefined) {
      writer.uint32(16).bool(message.getTapConfig);
    }
    if (message.setTapConfig !== undefined) {
      TapConfig.encode(message.setTapConfig, writer.uint32(26).fork()).ldelim();
    }
    if (message.getCarryConfig !== undefined) {
      writer.uint32(32).bool(message.getCarryConfig);
    }
    if (message.setCarryConfig !== undefined) {
      CarryConfig.encode(message.setCarryConfig, writer.uint32(42).fork()).ldelim();
    }
    if (message.saveState !== undefined) {
      writer.uint32(48).bool(message.saveState);
    }
    if (message.setLiveStream !== undefined) {
      writer.uint32(56).bool(message.setLiveStream);
    }
    if (message.getStillWakeConfig !== undefined) {
      writer.uint32(64).bool(message.getStillWakeConfig);
    }
    if (message.setStillWakeConfig !== undefined) {
      StillWakeConfig.encode(message.setStillWakeConfig, writer.uint32(74).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Request {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.getCapabilities = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.getTapConfig = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.setTapConfig = TapConfig.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.getCarryConfig = reader.bool();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.setCarryConfig = CarryConfig.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.saveState = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.setLiveStream = reader.bool();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.getStillWakeConfig = reader.bool();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.setStillWakeConfig = StillWakeConfig.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getCapabilities: isSet(object.getCapabilities) ? globalThis.Boolean(object.getCapabilities) : undefined,
      getTapConfig: isSet(object.getTapConfig) ? globalThis.Boolean(object.getTapConfig) : undefined,
      setTapConfig: isSet(object.setTapConfig) ? TapConfig.fromJSON(object.setTapConfig) : undefined,
      getCarryConfig: isSet(object.getCarryConfig) ? globalThis.Boolean(object.getCarryConfig) : undefined,
      setCarryConfig: isSet(object.setCarryConfig) ? CarryConfig.fromJSON(object.setCarryConfig) : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
      setLiveStream: isSet(object.setLiveStream) ? globalThis.Boolean(object.setLiveStream) : undefined,
      getStillWakeConfig: isSet(object.getStillWakeConfig) ? globalThis.Boolean(object.getStillWakeConfig) : undefined,
      setStillWakeConfig: isSet(object.setStillWakeConfig)
        ? StillWakeConfig.fromJSON(object.setStillWakeConfig)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getCapabilities !== undefined) {
      obj.getCapabilities = message.getCapabilities;
    }
    if (message.getTapConfig !== undefined) {
      obj.getTapConfig = message.getTapConfig;
    }
    if (message.setTapConfig !== undefined) {
      obj.setTapConfig = TapConfig.toJSON(message.setTapConfig);
    }
    if (message.getCarryConfig !== undefined) {
      obj.getCarryConfig = message.getCarryConfig;
    }
    if (message.setCarryConfig !== undefined) {
      obj.setCarryConfig = CarryConfig.toJSON(message.setCarryConfig);
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    if (message.setLiveStream !== undefined) {
      obj.setLiveStream = message.setLiveStream;
    }
    if (message.getStillWakeConfig !== undefined) {
      obj.getStillWakeConfig = message.getStillWakeConfig;
    }
    if (message.setStillWakeConfig !== undefined) {
      obj.setStillWakeConfig = StillWakeConfig.toJSON(message.setStillWakeConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getCapabilities = object.getCapabilities ?? undefined;
    message.getTapConfig = object.getTapConfig ?? undefined;
    message.setTapConfig = (object.setTapConfig !== undefined && object.setTapConfig !== null)
      ? TapConfig.fromPartial(object.setTapConfig)
      : undefined;
    message.getCarryConfig = object.getCarryConfig ?? undefined;
    message.setCarryConfig = (object.setCarryConfig !== undefined && object.setCarryConfig !== null)
      ? CarryConfig.fromPartial(object.setCarryConfig)
      : undefined;
    message.saveState = object.saveState ?? undefined;
    message.setLiveStream = object.setLiveStream ?? undefined;
    message.getStillWakeConfig = object.getStillWakeConfig ?? undefined;
    message.setStillWakeConfig = (object.setStillWakeConfig !== undefined && object.setStillWakeConfig !== null)
      ? StillWakeConfig.fromPartial(object.setStillWakeConfig)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return {
    capabilities: undefined,
    tapConfig: undefined,
    setTapConfig: undefined,
    carryConfig: undefined,
    setCarryConfig: undefined,
    saveState: undefined,
    setLiveStream: undefined,
    stillWakeConfig: undefined,
    setStillWakeConfig: undefined,
  };
}

export const Response = {
  encode(message: Response, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.capabilities !== undefined) {
      Capabilities.encode(message.capabilities, writer.uint32(10).fork()).ldelim();
    }
    if (message.tapConfig !== undefined) {
      TapConfig.encode(message.tapConfig, writer.uint32(18).fork()).ldelim();
    }
    if (message.setTapConfig !== undefined) {
      writer.uint32(24).bool(message.setTapConfig);
    }
    if (message.carryConfig !== undefined) {
      CarryConfig.encode(message.carryConfig, writer.uint32(34).fork()).ldelim();
    }
    if (message.setCarryConfig !== undefined) {
      writer.uint32(40).bool(message.setCarryConfig);
    }
    if (message.saveState !== undefined) {
      writer.uint32(48).bool(message.saveState);
    }
    if (message.setLiveStream !== undefined) {
      writer.uint32(56).bool(message.setLiveStream);
    }
    if (message.stillWakeConfig !== undefined) {
      StillWakeConfig.encode(message.stillWakeConfig, writer.uint32(66).fork()).ldelim();
    }
    if (message.setStillWakeConfig !== undefined) {
      writer.uint32(72).bool(message.setStillWakeConfig);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Response {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.capabilities = Capabilities.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.tapConfig = TapConfig.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.setTapConfig = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.carryConfig = CarryConfig.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.setCarryConfig = reader.bool();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.saveState = reader.bool();
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.setLiveStream = reader.bool();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.stillWakeConfig = StillWakeConfig.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.setStillWakeConfig = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      capabilities: isSet(object.capabilities) ? Capabilities.fromJSON(object.capabilities) : undefined,
      tapConfig: isSet(object.tapConfig) ? TapConfig.fromJSON(object.tapConfig) : undefined,
      setTapConfig: isSet(object.setTapConfig) ? globalThis.Boolean(object.setTapConfig) : undefined,
      carryConfig: isSet(object.carryConfig) ? CarryConfig.fromJSON(object.carryConfig) : undefined,
      setCarryConfig: isSet(object.setCarryConfig) ? globalThis.Boolean(object.setCarryConfig) : undefined,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : undefined,
      setLiveStream: isSet(object.setLiveStream) ? globalThis.Boolean(object.setLiveStream) : undefined,
      stillWakeConfig: isSet(object.stillWakeConfig) ? StillWakeConfig.fromJSON(object.stillWakeConfig) : undefined,
      setStillWakeConfig: isSet(object.setStillWakeConfig) ? globalThis.Boolean(object.setStillWakeConfig) : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.capabilities !== undefined) {
      obj.capabilities = Capabilities.toJSON(message.capabilities);
    }
    if (message.tapConfig !== undefined) {
      obj.tapConfig = TapConfig.toJSON(message.tapConfig);
    }
    if (message.setTapConfig !== undefined) {
      obj.setTapConfig = message.setTapConfig;
    }
    if (message.carryConfig !== undefined) {
      obj.carryConfig = CarryConfig.toJSON(message.carryConfig);
    }
    if (message.setCarryConfig !== undefined) {
      obj.setCarryConfig = message.setCarryConfig;
    }
    if (message.saveState !== undefined) {
      obj.saveState = message.saveState;
    }
    if (message.setLiveStream !== undefined) {
      obj.setLiveStream = message.setLiveStream;
    }
    if (message.stillWakeConfig !== undefined) {
      obj.stillWakeConfig = StillWakeConfig.toJSON(message.stillWakeConfig);
    }
    if (message.setStillWakeConfig !== undefined) {
      obj.setStillWakeConfig = message.setStillWakeConfig;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.capabilities = (object.capabilities !== undefined && object.capabilities !== null)
      ? Capabilities.fromPartial(object.capabilities)
      : undefined;
    message.tapConfig = (object.tapConfig !== undefined && object.tapConfig !== null)
      ? TapConfig.fromPartial(object.tapConfig)
      : undefined;
    message.setTapConfig = object.setTapConfig ?? undefined;
    message.carryConfig = (object.carryConfig !== undefined && object.carryConfig !== null)
      ? CarryConfig.fromPartial(object.carryConfig)
      : undefined;
    message.setCarryConfig = object.setCarryConfig ?? undefined;
    message.saveState = object.saveState ?? undefined;
    message.setLiveStream = object.setLiveStream ?? undefined;
    message.stillWakeConfig = (object.stillWakeConfig !== undefined && object.stillWakeConfig !== null)
      ? StillWakeConfig.fromPartial(object.stillWakeConfig)
      : undefined;
    message.setStillWakeConfig = object.setStillWakeConfig ?? undefined;
    return message;
  },
};

function createBaseCapabilities(): Capabilities {
  return {
    sensor: "",
    supportsTap: false,
    supportsDoubleTap: false,
    supportsCarry: false,
    thresholdMax: 0,
    supportsStillWake: false,
  };
}

export const Capabilities = {
  encode(message: Capabilities, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.sensor !== "") {
      writer.uint32(10).string(message.sensor);
    }
    if (message.supportsTap !== false) {
      writer.uint32(16).bool(message.supportsTap);
    }
    if (message.supportsDoubleTap !== false) {
      writer.uint32(24).bool(message.supportsDoubleTap);
    }
    if (message.supportsCarry !== false) {
      writer.uint32(32).bool(message.supportsCarry);
    }
    if (message.thresholdMax !== 0) {
      writer.uint32(40).uint32(message.thresholdMax);
    }
    if (message.supportsStillWake !== false) {
      writer.uint32(48).bool(message.supportsStillWake);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Capabilities {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCapabilities();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.sensor = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.supportsTap = reader.bool();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.supportsDoubleTap = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.supportsCarry = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.thresholdMax = reader.uint32();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.supportsStillWake = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Capabilities {
    return {
      sensor: isSet(object.sensor) ? globalThis.String(object.sensor) : "",
      supportsTap: isSet(object.supportsTap) ? globalThis.Boolean(object.supportsTap) : false,
      supportsDoubleTap: isSet(object.supportsDoubleTap) ? globalThis.Boolean(object.supportsDoubleTap) : false,
      supportsCarry: isSet(object.supportsCarry) ? globalThis.Boolean(object.supportsCarry) : false,
      thresholdMax: isSet(object.thresholdMax) ? globalThis.Number(object.thresholdMax) : 0,
      supportsStillWake: isSet(object.supportsStillWake) ? globalThis.Boolean(object.supportsStillWake) : false,
    };
  },

  toJSON(message: Capabilities): unknown {
    const obj: any = {};
    if (message.sensor !== "") {
      obj.sensor = message.sensor;
    }
    if (message.supportsTap !== false) {
      obj.supportsTap = message.supportsTap;
    }
    if (message.supportsDoubleTap !== false) {
      obj.supportsDoubleTap = message.supportsDoubleTap;
    }
    if (message.supportsCarry !== false) {
      obj.supportsCarry = message.supportsCarry;
    }
    if (message.thresholdMax !== 0) {
      obj.thresholdMax = Math.round(message.thresholdMax);
    }
    if (message.supportsStillWake !== false) {
      obj.supportsStillWake = message.supportsStillWake;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Capabilities>, I>>(base?: I): Capabilities {
    return Capabilities.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Capabilities>, I>>(object: I): Capabilities {
    const message = createBaseCapabilities();
    message.sensor = object.sensor ?? "";
    message.supportsTap = object.supportsTap ?? false;
    message.supportsDoubleTap = object.supportsDoubleTap ?? false;
    message.supportsCarry = object.supportsCarry ?? false;
    message.thresholdMax = object.thresholdMax ?? 0;
    message.supportsStillWake = object.supportsStillWake ?? false;
    return message;
  },
};

function createBaseTapConfig(): TapConfig {
  return {
    enabled: false,
    threshold: 0,
    timeLimitMs: 0,
    latencyMs: 0,
    windowMs: 0,
    leftSingleBinding: undefined,
    leftDoubleBinding: undefined,
    rightSingleBinding: undefined,
    rightDoubleBinding: undefined,
    layerMask: 0,
  };
}

export const TapConfig = {
  encode(message: TapConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.threshold !== 0) {
      writer.uint32(16).uint32(message.threshold);
    }
    if (message.timeLimitMs !== 0) {
      writer.uint32(24).uint32(message.timeLimitMs);
    }
    if (message.latencyMs !== 0) {
      writer.uint32(32).uint32(message.latencyMs);
    }
    if (message.windowMs !== 0) {
      writer.uint32(40).uint32(message.windowMs);
    }
    if (message.leftSingleBinding !== undefined) {
      BehaviorBinding.encode(message.leftSingleBinding, writer.uint32(50).fork()).ldelim();
    }
    if (message.leftDoubleBinding !== undefined) {
      BehaviorBinding.encode(message.leftDoubleBinding, writer.uint32(58).fork()).ldelim();
    }
    if (message.rightSingleBinding !== undefined) {
      BehaviorBinding.encode(message.rightSingleBinding, writer.uint32(66).fork()).ldelim();
    }
    if (message.rightDoubleBinding !== undefined) {
      BehaviorBinding.encode(message.rightDoubleBinding, writer.uint32(74).fork()).ldelim();
    }
    if (message.layerMask !== 0) {
      writer.uint32(80).uint32(message.layerMask);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TapConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTapConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.threshold = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.timeLimitMs = reader.uint32();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.latencyMs = reader.uint32();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.windowMs = reader.uint32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.leftSingleBinding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.leftDoubleBinding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.rightSingleBinding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.rightDoubleBinding = BehaviorBinding.decode(reader, reader.uint32());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.layerMask = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TapConfig {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      threshold: isSet(object.threshold) ? globalThis.Number(object.threshold) : 0,
      timeLimitMs: isSet(object.timeLimitMs) ? globalThis.Number(object.timeLimitMs) : 0,
      latencyMs: isSet(object.latencyMs) ? globalThis.Number(object.latencyMs) : 0,
      windowMs: isSet(object.windowMs) ? globalThis.Number(object.windowMs) : 0,
      leftSingleBinding: isSet(object.leftSingleBinding)
        ? BehaviorBinding.fromJSON(object.leftSingleBinding)
        : undefined,
      leftDoubleBinding: isSet(object.leftDoubleBinding)
        ? BehaviorBinding.fromJSON(object.leftDoubleBinding)
        : undefined,
      rightSingleBinding: isSet(object.rightSingleBinding)
        ? BehaviorBinding.fromJSON(object.rightSingleBinding)
        : undefined,
      rightDoubleBinding: isSet(object.rightDoubleBinding)
        ? BehaviorBinding.fromJSON(object.rightDoubleBinding)
        : undefined,
      layerMask: isSet(object.layerMask) ? globalThis.Number(object.layerMask) : 0,
    };
  },

  toJSON(message: TapConfig): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.threshold !== 0) {
      obj.threshold = Math.round(message.threshold);
    }
    if (message.timeLimitMs !== 0) {
      obj.timeLimitMs = Math.round(message.timeLimitMs);
    }
    if (message.latencyMs !== 0) {
      obj.latencyMs = Math.round(message.latencyMs);
    }
    if (message.windowMs !== 0) {
      obj.windowMs = Math.round(message.windowMs);
    }
    if (message.leftSingleBinding !== undefined) {
      obj.leftSingleBinding = BehaviorBinding.toJSON(message.leftSingleBinding);
    }
    if (message.leftDoubleBinding !== undefined) {
      obj.leftDoubleBinding = BehaviorBinding.toJSON(message.leftDoubleBinding);
    }
    if (message.rightSingleBinding !== undefined) {
      obj.rightSingleBinding = BehaviorBinding.toJSON(message.rightSingleBinding);
    }
    if (message.rightDoubleBinding !== undefined) {
      obj.rightDoubleBinding = BehaviorBinding.toJSON(message.rightDoubleBinding);
    }
    if (message.layerMask !== 0) {
      obj.layerMask = Math.round(message.layerMask);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TapConfig>, I>>(base?: I): TapConfig {
    return TapConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TapConfig>, I>>(object: I): TapConfig {
    const message = createBaseTapConfig();
    message.enabled = object.enabled ?? false;
    message.threshold = object.threshold ?? 0;
    message.timeLimitMs = object.timeLimitMs ?? 0;
    message.latencyMs = object.latencyMs ?? 0;
    message.windowMs = object.windowMs ?? 0;
    message.leftSingleBinding = (object.leftSingleBinding !== undefined && object.leftSingleBinding !== null)
      ? BehaviorBinding.fromPartial(object.leftSingleBinding)
      : undefined;
    message.leftDoubleBinding = (object.leftDoubleBinding !== undefined && object.leftDoubleBinding !== null)
      ? BehaviorBinding.fromPartial(object.leftDoubleBinding)
      : undefined;
    message.rightSingleBinding = (object.rightSingleBinding !== undefined && object.rightSingleBinding !== null)
      ? BehaviorBinding.fromPartial(object.rightSingleBinding)
      : undefined;
    message.rightDoubleBinding = (object.rightDoubleBinding !== undefined && object.rightDoubleBinding !== null)
      ? BehaviorBinding.fromPartial(object.rightDoubleBinding)
      : undefined;
    message.layerMask = object.layerMask ?? 0;
    return message;
  },
};

function createBaseCarryConfig(): CarryConfig {
  return { enabled: false, motionThreshold: 0, motionDurationMs: 0 };
}

export const CarryConfig = {
  encode(message: CarryConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.motionThreshold !== 0) {
      writer.uint32(16).uint32(message.motionThreshold);
    }
    if (message.motionDurationMs !== 0) {
      writer.uint32(24).uint32(message.motionDurationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CarryConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCarryConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.motionThreshold = reader.uint32();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.motionDurationMs = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CarryConfig {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      motionThreshold: isSet(object.motionThreshold) ? globalThis.Number(object.motionThreshold) : 0,
      motionDurationMs: isSet(object.motionDurationMs) ? globalThis.Number(object.motionDurationMs) : 0,
    };
  },

  toJSON(message: CarryConfig): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.motionThreshold !== 0) {
      obj.motionThreshold = Math.round(message.motionThreshold);
    }
    if (message.motionDurationMs !== 0) {
      obj.motionDurationMs = Math.round(message.motionDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CarryConfig>, I>>(base?: I): CarryConfig {
    return CarryConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CarryConfig>, I>>(object: I): CarryConfig {
    const message = createBaseCarryConfig();
    message.enabled = object.enabled ?? false;
    message.motionThreshold = object.motionThreshold ?? 0;
    message.motionDurationMs = object.motionDurationMs ?? 0;
    return message;
  },
};

function createBaseStillWakeConfig(): StillWakeConfig {
  return { enabled: false, settleDurationMs: 0 };
}

export const StillWakeConfig = {
  encode(message: StillWakeConfig, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.enabled !== false) {
      writer.uint32(8).bool(message.enabled);
    }
    if (message.settleDurationMs !== 0) {
      writer.uint32(16).uint32(message.settleDurationMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StillWakeConfig {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStillWakeConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.settleDurationMs = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StillWakeConfig {
    return {
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
      settleDurationMs: isSet(object.settleDurationMs) ? globalThis.Number(object.settleDurationMs) : 0,
    };
  },

  toJSON(message: StillWakeConfig): unknown {
    const obj: any = {};
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    if (message.settleDurationMs !== 0) {
      obj.settleDurationMs = Math.round(message.settleDurationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StillWakeConfig>, I>>(base?: I): StillWakeConfig {
    return StillWakeConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StillWakeConfig>, I>>(object: I): StillWakeConfig {
    const message = createBaseStillWakeConfig();
    message.enabled = object.enabled ?? false;
    message.settleDurationMs = object.settleDurationMs ?? 0;
    return message;
  },
};

function createBaseLiveState(): LiveState {
  return { magnitude: 0, orientation: 0, carryActive: false, tapDetected: false, lastClickSrc: 0 };
}

export const LiveState = {
  encode(message: LiveState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.magnitude !== 0) {
      writer.uint32(8).uint32(message.magnitude);
    }
    if (message.orientation !== 0) {
      writer.uint32(16).int32(message.orientation);
    }
    if (message.carryActive !== false) {
      writer.uint32(24).bool(message.carryActive);
    }
    if (message.tapDetected !== false) {
      writer.uint32(32).bool(message.tapDetected);
    }
    if (message.lastClickSrc !== 0) {
      writer.uint32(40).uint32(message.lastClickSrc);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): LiveState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLiveState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.magnitude = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.orientation = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.carryActive = reader.bool();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.tapDetected = reader.bool();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.lastClickSrc = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LiveState {
    return {
      magnitude: isSet(object.magnitude) ? globalThis.Number(object.magnitude) : 0,
      orientation: isSet(object.orientation) ? orientationFromJSON(object.orientation) : 0,
      carryActive: isSet(object.carryActive) ? globalThis.Boolean(object.carryActive) : false,
      tapDetected: isSet(object.tapDetected) ? globalThis.Boolean(object.tapDetected) : false,
      lastClickSrc: isSet(object.lastClickSrc) ? globalThis.Number(object.lastClickSrc) : 0,
    };
  },

  toJSON(message: LiveState): unknown {
    const obj: any = {};
    if (message.magnitude !== 0) {
      obj.magnitude = Math.round(message.magnitude);
    }
    if (message.orientation !== 0) {
      obj.orientation = orientationToJSON(message.orientation);
    }
    if (message.carryActive !== false) {
      obj.carryActive = message.carryActive;
    }
    if (message.tapDetected !== false) {
      obj.tapDetected = message.tapDetected;
    }
    if (message.lastClickSrc !== 0) {
      obj.lastClickSrc = Math.round(message.lastClickSrc);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LiveState>, I>>(base?: I): LiveState {
    return LiveState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LiveState>, I>>(object: I): LiveState {
    const message = createBaseLiveState();
    message.magnitude = object.magnitude ?? 0;
    message.orientation = object.orientation ?? 0;
    message.carryActive = object.carryActive ?? false;
    message.tapDetected = object.tapDetected ?? false;
    message.lastClickSrc = object.lastClickSrc ?? 0;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { liveState: undefined };
}

export const Notification = {
  encode(message: Notification, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.liveState !== undefined) {
      LiveState.encode(message.liveState, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Notification {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.liveState = LiveState.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Notification {
    return { liveState: isSet(object.liveState) ? LiveState.fromJSON(object.liveState) : undefined };
  },

  toJSON(message: Notification): unknown {
    const obj: any = {};
    if (message.liveState !== undefined) {
      obj.liveState = LiveState.toJSON(message.liveState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Notification>, I>>(base?: I): Notification {
    return Notification.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Notification>, I>>(object: I): Notification {
    const message = createBaseNotification();
    message.liveState = (object.liveState !== undefined && object.liveState !== null)
      ? LiveState.fromPartial(object.liveState)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
